// GENERATED by scripts/gen_ts_types.py from src/cola_coder/ui/schemas.py — DO NOT EDIT.

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export interface TrainingStatus {
  alive: boolean;
  step: number | null;
  total_steps: number | null;
  progress_pct: number | null;
  loss: number | null;
  ppl: number | null;
  tok_per_s: number | null;
  s_per_it: number | null;
  last_log_line: string | null;
}

export interface SystemStatus {
  gpu_name: string | null;
  gpu_util_pct: number | null;
  gpu_mem_used_mb: number | null;
  gpu_mem_total_mb: number | null;
  gpu_power_w: number | null;
}

export interface Checkpoint {
  model: string;
  name: string;
  step: number;
  loss: number | null;
  path: string;
  mtime: number;
}

export interface StatusResponse {
  training: TrainingStatus;
  system: SystemStatus;
  checkpoints: Checkpoint[];
}

export interface Dataset {
  name: string;
  path: string;
  kind: 'npy' | 'jsonl';
  size_bytes: number;
  mtime: number;
  has_weights: boolean;
  num_samples: number | null;
}

export interface Job {
  id: string;
  name: string;
  pid: number;
  status: 'running' | 'done' | 'failed';
  cmd: string[];
  log: string;
  started: number;
  returncode: number | null;
}

export interface ActionDef {
  key: string;
  script: string;
  label: string;
  args: string[];
  trainer?: boolean;
  gpu?: boolean;
}

export interface JobLogChunk {
  text: string;
  done: boolean;
}

export interface SftFile {
  name: string;
  path: string;
  kind: string;
  num_records: number;
  size_bytes: number;
  mtime: number;
}

export interface SftPreview {
  path: string;
  records: Record<string, JsonValue>[];
  fields: string[];
  count: number;
  truncated: boolean;
}

export interface ScriptInfo {
  name: string;
  category: string;
  purpose: string;
  exists: boolean;
}

export interface ScriptsCatalog {
  scripts: ScriptInfo[];
  categories: string[];
  count: number;
  on_disk: number;
}

export interface ScoreSummary {
  n: number;
  mean: number;
  min: number;
  max: number;
  histogram: number[];
  bins: number[];
}

export interface Preview {
  kind: string;
  num_samples?: number | null;
  shape?: number[] | null;
  dtype?: string | null;
  preview?: JsonValue[] | null;
  error?: string | null;
}

export interface ConfigFile {
  name: string;
  path: string;
  rel: string;
  size_bytes: number;
  mtime: number;
}

export interface ConfigContent {
  path?: string | null;
  content?: string | null;
  parsed?: JsonValue;
  truncated?: boolean | null;
  error?: string | null;
}

export interface PipelineRun {
  name: string;
  path: string;
  mtime: number;
  num_stages: number | null;
  status: string | null;
  completed: number | null;
  error?: string | null;
}

export interface PipelineStageState {
  num: number;
  name: string;
  description: string;
  optional: boolean;
  status: string;
  artifact: string;
  override: string;
  error: string;
  duration_secs: number;
  started_at?: string | null;
  completed_at?: string | null;
}

export interface PipelineRunDetail {
  name: string;
  config_path: string;
  created_at: string;
  updated_at: string;
  notes: string;
  stages: PipelineStageState[];
  num_stages: number;
  active_stages: number;
  completed: number;
  status: string;
}

export interface PipelineDeleteResult {
  ok: boolean;
  name: string;
}

export interface EvalResult {
  name: string;
  path: string;
  kind: string;
  mtime: number;
  summary: string;
}

export interface EvalDetail {
  path: string;
  kind: string;
  parsed: JsonValue;
  content: string | null;
  truncated: boolean;
}

export interface LogFile {
  name: string;
  path: string;
  size_bytes: number;
  mtime: number;
}

export interface LogTail {
  path: string;
  lines: string[];
  size_bytes: number;
  truncated: boolean;
}

export interface FeatureItem {
  key: string;
  enabled: boolean;
  value: JsonValue;
}

export interface FeatureGroup {
  category: string;
  features: FeatureItem[];
}

export interface FeaturesView {
  path: string;
  total: number;
  enabled: number;
  groups: FeatureGroup[];
}

export interface ReasoningSummary {
  advantage_norm: JsonValue;
  clip_epsilon: JsonValue;
  clip_epsilon_high: JsonValue;
  group_size: JsonValue;
  sft_warmup_enabled: boolean | null;
  problem_source: JsonValue;
}

export interface ReasoningView {
  path: string;
  parsed: Record<string, JsonValue>;
  reasoning: Record<string, JsonValue>;
  problem_set: Record<string, JsonValue>;
  sft_warmup: Record<string, JsonValue>;
  summary: ReasoningSummary;
}

export interface TokenizerInfo {
  path: string;
  vocab_size: number;
  n_merges: number;
  special_tokens: string[];
  has_fim_tokens: boolean;
  digit_splitting: boolean;
  model_type: string;
}

export interface CheckpointDetail {
  path: string;
  metadata: Record<string, JsonValue> | null;
  is_moe: boolean;
  moe_config: Record<string, JsonValue> | null;
  has_training_state: boolean;
  num_params: number;
  tensor_count: number;
  dtypes: string[];
  files: string[];
}

export interface RouterCheckpoint {
  path: string;
  name: string;
  step: number | null;
}

export interface RouterOverview {
  has_router: boolean;
  checkpoints: RouterCheckpoint[];
  domains: string[];
}

export interface ExportFormat {
  key: string;
  label: string;
  desc: string;
}

export interface ExportItem {
  path: string;
  format: string;
  size_bytes: number;
  mtime: number;
}

export interface ExportCheckpoint {
  model: string;
  name: string;
  step: number | null;
  path: string;
}

export interface ExportOverview {
  checkpoints: ExportCheckpoint[];
  formats: ExportFormat[];
  existing: ExportItem[];
}

export interface MetricPoint {
  step: number;
  loss: number | null;
  ppl: number | null;
  lr: number | null;
  tok_s: number | null;
}

export interface MetricsHistory {
  points: MetricPoint[];
  count: number;
}

export interface DataSource {
  name: string;
  weight: number | null;
  dataset: string | null;
  languages: string[];
  kind: string | null;
}

export interface DataSourcesView {
  path: string;
  sources: DataSource[];
  total_weight: number | null;
  parsed: Record<string, JsonValue>;
  summary: string;
}

export interface EvalSnapshot {
  step: number | null;
  path: string;
  mtime: number;
  metrics: Record<string, JsonValue>;
}

export interface EvalHistoryView {
  snapshots: EvalSnapshot[];
  count: number;
  metric_keys: string[];
}

export interface TokenizeResult {
  path: string;
  count: number;
  ids: number[];
  tokens: string[];
  truncated?: boolean;
}

export interface HealthCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export interface HealthSummary {
  score: number;
  checks: HealthCheck[];
  summary: string;
}

export interface StorageEntry {
  name: string;
  path: string;
  exists: boolean;
  size_bytes: number | null;
}

export interface StorageView {
  path: string;
  raw: Record<string, JsonValue>;
  tokenizer_path: string | null;
  data_dir: string | null;
  checkpoint_dir: string | null;
  entries: StorageEntry[];
}

export interface CompareDiff {
  num_params_delta: number;
  tensor_count_delta: number;
  is_moe_changed: boolean;
  metadata_changed_keys: string[];
  dtypes_only_a: string[];
  dtypes_only_b: string[];
}

export interface CompareResult {
  a: CheckpointDetail;
  b: CheckpointDetail;
  diff: CompareDiff;
}

export interface ModelCard {
  path: string;
  name: string;
  num_params: number;
  architecture: Record<string, JsonValue>;
  training: Record<string, JsonValue>;
  tokenizer: Record<string, JsonValue> | null;
  is_moe: boolean;
  markdown: string;
}

export interface FeatureSetResult {
  ok: true;
  key: string;
  enabled: boolean;
  path: string;
}

export interface ConfigChange {
  key: string;
  a: JsonValue;
  b: JsonValue;
}

export interface ConfigDiffSide {
  path: string;
  parsed: Record<string, JsonValue>;
}

export interface ConfigDiff {
  a: ConfigDiffSide;
  b: ConfigDiffSide;
  changed: ConfigChange[];
  only_a: string[];
  only_b: string[];
}

export interface GpuInfo {
  name: string;
  mem_total_mb: number | null;
  mem_used_mb: number | null;
  util_pct: number | null;
}

export interface DiskInfo {
  path: string;
  total_bytes: number | null;
  free_bytes: number | null;
  used_bytes: number | null;
}

export interface SystemInfo {
  python_version: string;
  platform: string;
  packages: Record<string, string | null>;
  gpus: GpuInfo[];
  disk: DiskInfo;
}

export interface TokenizerHealthItem {
  name: string;
  ok: boolean;
  detail: string;
}

export interface TokenizerHealthReport {
  path: string;
  vocab_size: number;
  checks: TokenizerHealthItem[];
  passed: number;
  failed: number;
  ok: boolean;
}

export interface WeightTier {
  label: string;
  count: number;
  pct: number;
}

export interface DataStats {
  data_path: string;
  file_size_mb: number;
  shape: number[];
  num_chunks: number;
  seq_len?: number | null;
  total_tokens: number;
  token_min: number;
  token_max: number;
  token_mean: number;
  est_unique_tokens?: number | null;
  has_weights?: boolean;
  weights_path?: string | null;
  weight_tiers?: WeightTier[];
  weight_mean?: number | null;
  weight_std?: number | null;
}

export interface CheckpointHealth {
  path: string;
  model: string;
  step: number;
  loss: number | null;
  size_mb: number;
  num_tensors: number | null;
  files: string[];
  config_stem: string | null;
  ok: boolean;
}

export interface MemoryEntry {
  id: string;
  type: string;
  created_at: string;
  content_preview: string;
}

export interface MemoryStats {
  total_entries: number;
  pinned: number;
  types: string[];
  size_bytes: number;
  oldest_at: string | null;
  newest_at: string | null;
  recent_sample: MemoryEntry[];
}

export interface IndexStats {
  exists: boolean;
  doc_count: number;
  chunk_count: number | null;
  embedding_model: string | null;
  embedding_dim: number | null;
  size_bytes: number;
  path: string | null;
  last_updated: string | null;
}

export interface ThreatInfo {
  file_path: string;
  name: string;
  severity: string;
  scanner: string;
  details: string | null;
}

export interface MalwareScanResult {
  path: string;
  files_scanned: number;
  is_clean: boolean;
  threats: ThreatInfo[];
  duration_ms: number;
}

export interface EnvCheckItem {
  name: string;
  ok: boolean;
  value: string;
  detail: string | null;
}

export interface EnvCheckReport {
  python_version: string;
  torch_version: string | null;
  cuda_available: boolean;
  gpu_name: string | null;
  vram_gb: number | null;
  hf_token_set: boolean;
  passed: number;
  failed: number;
  ok: boolean;
  checks: EnvCheckItem[];
}

export interface VramComponent {
  name: string;
  mb: number;
}

export interface VramEstimate {
  config: string;
  params_millions: number;
  precision: string;
  batch_size: number;
  seq_len: number;
  components: VramComponent[];
  total_mb: number;
  budget_mb: number;
  fits: boolean;
}

export interface HealthDimension {
  name: string;
  score: number;
  detail: string;
}

export interface ProjectHealthReport {
  overall_score: number;
  grade: string;
  dimensions: HealthDimension[];
  summary: string;
}

export interface ApiError {
  error: string;
}

export function isApiError<T>(v: T | ApiError): v is ApiError {
  return (
    typeof v === 'object' &&
    v !== null &&
    !Array.isArray(v) &&
    typeof (v as ApiError).error === 'string'
  );
}

export type JobOrError = Job | ApiError;
export type EvalDetailOrError = EvalDetail | ApiError;
export type LogTailOrError = LogTail | ApiError;
export type FeaturesViewOrError = FeaturesView | ApiError;
export type ReasoningViewOrError = ReasoningView | ApiError;
export type TokenizerInfoOrError = TokenizerInfo | ApiError;
export type CheckpointDetailOrError = CheckpointDetail | ApiError;
export type RouterOverviewOrError = RouterOverview | ApiError;
export type ExportOverviewOrError = ExportOverview | ApiError;
export type MetricsHistoryOrError = MetricsHistory | ApiError;
export type DataSourcesViewOrError = DataSourcesView | ApiError;
export type EvalHistoryViewOrError = EvalHistoryView | ApiError;
export type TokenizeResultOrError = TokenizeResult | ApiError;
export type HealthSummaryOrError = HealthSummary | ApiError;
export type SftPreviewOrError = SftPreview | ApiError;
export type ScriptsCatalogOrError = ScriptsCatalog | ApiError;
export type StorageViewOrError = StorageView | ApiError;
export type CompareResultOrError = CompareResult | ApiError;
export type ModelCardOrError = ModelCard | ApiError;
export type FeatureSetResultOrError = FeatureSetResult | ApiError;
export type ConfigDiffOrError = ConfigDiff | ApiError;
export type SystemInfoOrError = SystemInfo | ApiError;
export type PipelineRunDetailOrError = PipelineRunDetail | ApiError;
export type PipelineDeleteResultOrError = PipelineDeleteResult | ApiError;
export type TokenizerHealthReportOrError = TokenizerHealthReport | ApiError;
export type DataStatsOrError = DataStats | ApiError;
export type CheckpointHealthOrError = CheckpointHealth | ApiError;
export type MemoryStatsOrError = MemoryStats | ApiError;
export type IndexStatsOrError = IndexStats | ApiError;
export type MalwareScanResultOrError = MalwareScanResult | ApiError;
export type EnvCheckReportOrError = EnvCheckReport | ApiError;
export type VramEstimateOrError = VramEstimate | ApiError;
export type ProjectHealthReportOrError = ProjectHealthReport | ApiError;
