// GENERATED by scripts/gen_ts_types.py from src/cola_coder/ui/schemas.py — DO NOT EDIT.

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export interface TrainingStatus {
  alive: boolean;
  step: number | null;
  total_steps: number | null;
  progress_pct: number | null;
  loss: number | null;
  ppl: number | null;
  tok_per_s: number | null;
  s_per_it: number | null;
  last_log_line: string | null;
  step_stalled_s?: number | null;
  eta?: string | null;
}

export interface SystemStatus {
  gpu_name: string | null;
  gpu_util_pct: number | null;
  gpu_mem_used_mb: number | null;
  gpu_mem_total_mb: number | null;
  gpu_power_w: number | null;
}

export interface Checkpoint {
  model: string;
  name: string;
  step: number;
  loss: number | null;
  path: string;
  mtime: number;
}

export interface StatusResponse {
  training: TrainingStatus;
  system: SystemStatus;
  checkpoints: Checkpoint[];
}

export interface ScoreSnippetRequest {
  code: string;
}

export interface ScorerBreakdown {
  name: string;
  score: number;
  tier: string;
}

export interface SnippetScores {
  scorers: ScorerBreakdown[];
  mean_score: number;
  mean_tier: string;
  count: number;
}

export interface Dataset {
  name: string;
  path: string;
  kind: 'npy' | 'jsonl';
  size_bytes: number;
  mtime: number;
  has_weights: boolean;
  num_samples: number | null;
}

export interface Job {
  id: string;
  name: string;
  pid: number;
  status: 'running' | 'done' | 'failed';
  cmd: string[];
  log: string;
  started: number;
  returncode: number | null;
}

export interface ActionParam {
  name: string;
  flag: string;
  label: string;
  type: 'string' | 'int' | 'float' | 'bool' | 'choice' | 'config' | 'checkpoint' | 'path';
  default?: string | null;
  choices?: string[];
  required?: boolean;
  help?: string | null;
}

export interface ActionDef {
  key: string;
  script: string;
  label: string;
  args: string[];
  trainer?: boolean;
  gpu?: boolean;
  params?: ActionParam[];
  category?: 'Data' | 'Training' | 'Pipeline' | 'Evaluation' | 'Inspection' | 'Export' | 'Tools';
}

export interface JobLogChunk {
  text: string;
  done: boolean;
}

export interface SftFile {
  name: string;
  path: string;
  kind: string;
  num_records: number;
  size_bytes: number;
  mtime: number;
}

export interface SftPreview {
  path: string;
  records: Record<string, JsonValue>[];
  fields: string[];
  count: number;
  truncated: boolean;
}

export interface ScriptInfo {
  name: string;
  category: string;
  purpose: string;
  exists: boolean;
}

export interface ScriptsCatalog {
  scripts: ScriptInfo[];
  categories: string[];
  count: number;
  on_disk: number;
}

export interface ScoreSummary {
  n: number;
  mean: number;
  min: number;
  max: number;
  histogram: number[];
  bins: number[];
}

export interface Preview {
  kind: string;
  num_samples?: number | null;
  shape?: number[] | null;
  dtype?: string | null;
  preview?: JsonValue[] | null;
  error?: string | null;
}

export interface ConfigFile {
  name: string;
  path: string;
  rel: string;
  size_bytes: number;
  mtime: number;
}

export interface ConfigContent {
  path?: string | null;
  content?: string | null;
  parsed?: JsonValue;
  truncated?: boolean | null;
  error?: string | null;
}

export interface PipelineRun {
  name: string;
  path: string;
  mtime: number;
  num_stages: number | null;
  status: string | null;
  completed: number | null;
  error?: string | null;
}

export interface PipelineStageState {
  num: number;
  name: string;
  description: string;
  optional: boolean;
  status: string;
  artifact: string;
  override: string;
  error: string;
  duration_secs: number;
  started_at?: string | null;
  completed_at?: string | null;
}

export interface PipelineRunDetail {
  name: string;
  config_path: string;
  created_at: string;
  updated_at: string;
  notes: string;
  stages: PipelineStageState[];
  num_stages: number;
  active_stages: number;
  completed: number;
  status: string;
}

export interface PipelineDeleteResult {
  ok: boolean;
  name: string;
}

export interface EvalResult {
  name: string;
  path: string;
  kind: string;
  mtime: number;
  summary: string;
}

export interface EvalDetail {
  path: string;
  kind: string;
  parsed: JsonValue;
  content: string | null;
  truncated: boolean;
}

export interface LogFile {
  name: string;
  path: string;
  size_bytes: number;
  mtime: number;
}

export interface LogTail {
  path: string;
  lines: string[];
  size_bytes: number;
  truncated: boolean;
}

export interface FeatureItem {
  key: string;
  enabled: boolean;
  value: JsonValue;
}

export interface FeatureGroup {
  category: string;
  features: FeatureItem[];
}

export interface FeaturesView {
  path: string;
  total: number;
  enabled: number;
  groups: FeatureGroup[];
}

export interface ReasoningSummary {
  advantage_norm: JsonValue;
  clip_epsilon: JsonValue;
  clip_epsilon_high: JsonValue;
  group_size: JsonValue;
  sft_warmup_enabled: boolean | null;
  problem_source: JsonValue;
}

export interface ReasoningView {
  path: string;
  parsed: Record<string, JsonValue>;
  reasoning: Record<string, JsonValue>;
  problem_set: Record<string, JsonValue>;
  sft_warmup: Record<string, JsonValue>;
  summary: ReasoningSummary;
}

export interface TokenizerInfo {
  path: string;
  vocab_size: number;
  n_merges: number;
  special_tokens: string[];
  has_fim_tokens: boolean;
  digit_splitting: boolean;
  model_type: string;
}

export interface CheckpointDetail {
  path: string;
  metadata: Record<string, JsonValue> | null;
  is_moe: boolean;
  moe_config: Record<string, JsonValue> | null;
  has_training_state: boolean;
  num_params: number;
  tensor_count: number;
  dtypes: string[];
  files: string[];
}

export interface CheckpointNote {
  key: string;
  label: string;
  note: string;
  updated_at: string;
}

export interface CheckpointNotes {
  notes: CheckpointNote[];
}

export interface CheckpointNoteSetRequest {
  key: string;
  label?: string;
  note?: string;
}

export interface CheckpointNoteDeleteRequest {
  key: string;
}

export interface RouterCheckpoint {
  path: string;
  name: string;
  step: number | null;
}

export interface RouterOverview {
  has_router: boolean;
  checkpoints: RouterCheckpoint[];
  domains: string[];
}

export interface ExportFormat {
  key: string;
  label: string;
  desc: string;
}

export interface ExportItem {
  path: string;
  format: string;
  size_bytes: number;
  mtime: number;
}

export interface ExportCheckpoint {
  model: string;
  name: string;
  step: number | null;
  path: string;
}

export interface ExportOverview {
  checkpoints: ExportCheckpoint[];
  formats: ExportFormat[];
  existing: ExportItem[];
}

export interface MetricPoint {
  step: number;
  loss: number | null;
  ppl: number | null;
  lr: number | null;
  tok_s: number | null;
}

export interface MetricsHistory {
  points: MetricPoint[];
  count: number;
}

export interface DataSource {
  name: string;
  weight: number | null;
  dataset: string | null;
  languages: string[];
  kind: string | null;
}

export interface DataSourcesView {
  path: string;
  sources: DataSource[];
  total_weight: number | null;
  parsed: Record<string, JsonValue>;
  summary: string;
}

export interface EvalSnapshot {
  step: number | null;
  path: string;
  mtime: number;
  metrics: Record<string, JsonValue>;
}

export interface EvalHistoryView {
  snapshots: EvalSnapshot[];
  count: number;
  metric_keys: string[];
}

export interface TokenizeResult {
  path: string;
  count: number;
  ids: number[];
  tokens: string[];
  truncated?: boolean;
}

export interface HealthCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export interface HealthSummary {
  score: number;
  checks: HealthCheck[];
  summary: string;
}

export interface StorageEntry {
  name: string;
  path: string;
  exists: boolean;
  size_bytes: number | null;
}

export interface StorageView {
  path: string;
  raw: Record<string, JsonValue>;
  tokenizer_path: string | null;
  data_dir: string | null;
  checkpoint_dir: string | null;
  entries: StorageEntry[];
}

export interface CompareDiff {
  num_params_delta: number;
  tensor_count_delta: number;
  is_moe_changed: boolean;
  metadata_changed_keys: string[];
  dtypes_only_a: string[];
  dtypes_only_b: string[];
}

export interface CompareResult {
  a: CheckpointDetail;
  b: CheckpointDetail;
  diff: CompareDiff;
}

export interface ModelCard {
  path: string;
  name: string;
  num_params: number;
  architecture: Record<string, JsonValue>;
  training: Record<string, JsonValue>;
  tokenizer: Record<string, JsonValue> | null;
  is_moe: boolean;
  markdown: string;
}

export interface FeatureSetResult {
  ok: true;
  key: string;
  enabled: boolean;
  path: string;
}

export interface ConfigChange {
  key: string;
  a: JsonValue;
  b: JsonValue;
}

export interface ConfigDiffSide {
  path: string;
  parsed: Record<string, JsonValue>;
}

export interface ConfigDiff {
  a: ConfigDiffSide;
  b: ConfigDiffSide;
  changed: ConfigChange[];
  only_a: string[];
  only_b: string[];
}

export interface GpuInfo {
  name: string;
  mem_total_mb: number | null;
  mem_used_mb: number | null;
  util_pct: number | null;
}

export interface DiskInfo {
  path: string;
  total_bytes: number | null;
  free_bytes: number | null;
  used_bytes: number | null;
}

export interface SystemInfo {
  python_version: string;
  platform: string;
  packages: Record<string, string | null>;
  gpus: GpuInfo[];
  disk: DiskInfo;
}

export interface TokenizerHealthItem {
  name: string;
  ok: boolean;
  detail: string;
}

export interface TokenizerHealthReport {
  path: string;
  vocab_size: number;
  checks: TokenizerHealthItem[];
  passed: number;
  failed: number;
  ok: boolean;
}

export interface WeightTier {
  label: string;
  count: number;
  pct: number;
}

export interface DataStats {
  data_path: string;
  file_size_mb: number;
  shape: number[];
  num_chunks: number;
  seq_len?: number | null;
  total_tokens: number;
  token_min: number;
  token_max: number;
  token_mean: number;
  est_unique_tokens?: number | null;
  has_weights?: boolean;
  weights_path?: string | null;
  weight_tiers?: WeightTier[];
  weight_mean?: number | null;
  weight_std?: number | null;
}

export interface CheckpointHealth {
  path: string;
  model: string;
  step: number;
  loss: number | null;
  size_mb: number;
  num_tensors: number | null;
  files: string[];
  config_stem: string | null;
  ok: boolean;
}

export interface MemoryEntry {
  id: string;
  type: string;
  created_at: string;
  content_preview: string;
}

export interface MemoryStats {
  total_entries: number;
  pinned: number;
  types: string[];
  size_bytes: number;
  oldest_at: string | null;
  newest_at: string | null;
  recent_sample: MemoryEntry[];
}

export interface MemoryFile {
  type: string;
  name: string;
  content: string;
  truncated: boolean;
  entry_count: number;
}

export interface MemoryExport {
  initialized: boolean;
  files: MemoryFile[];
}

export interface MemoryAddRequest {
  kind: 'pattern' | 'error' | 'decision' | 'domain' | 'session';
  primary: string;
  secondary?: string;
}

export interface MemorySearchRequest {
  query: string;
  max_chunks?: number;
}

export interface MemoryChunkOut {
  content: string;
  source_file: string;
  section: string;
  relevance_score: number;
}

export interface MemorySearchResult {
  query: string;
  results: MemoryChunkOut[];
}

export interface MemoryFileCount {
  name: string;
  removed: number;
}

export interface MemoryCompactResult {
  removed_total: number;
  removed: MemoryFileCount[];
}

export interface IndexStats {
  exists: boolean;
  doc_count: number;
  chunk_count: number | null;
  embedding_model: string | null;
  embedding_dim: number | null;
  size_bytes: number;
  path: string | null;
  last_updated: string | null;
}

export interface ThreatInfo {
  file_path: string;
  name: string;
  severity: string;
  scanner: string;
  details: string | null;
}

export interface MalwareScanResult {
  path: string;
  files_scanned: number;
  is_clean: boolean;
  threats: ThreatInfo[];
  duration_ms: number;
}

export interface EnvCheckItem {
  name: string;
  ok: boolean;
  value: string;
  detail: string | null;
}

export interface EnvCheckReport {
  python_version: string;
  torch_version: string | null;
  cuda_available: boolean;
  gpu_name: string | null;
  vram_gb: number | null;
  hf_token_set: boolean;
  passed: number;
  failed: number;
  ok: boolean;
  checks: EnvCheckItem[];
}

export interface VramComponent {
  name: string;
  mb: number;
}

export interface VramEstimate {
  config: string;
  params_millions: number;
  precision: string;
  batch_size: number;
  seq_len: number;
  components: VramComponent[];
  total_mb: number;
  budget_mb: number;
  fits: boolean;
}

export interface HealthDimension {
  name: string;
  score: number;
  detail: string;
}

export interface ProjectHealthReport {
  overall_score: number;
  grade: string;
  dimensions: HealthDimension[];
  summary: string;
}

export interface BenchmarkRun {
  name: string;
  path: string;
  kind: string;
  tokens_per_s: number | null;
  latency_ms: number | null;
  config: string | null;
  checkpoint: string | null;
  mtime: number;
}

export interface BenchmarkResults {
  runs: BenchmarkRun[];
  count: number;
}

export interface SafetyProbe {
  suite: string;
  name: string;
  passed: boolean;
  detail: string | null;
}

export interface SafetyEvalRun {
  name: string;
  path: string;
  checkpoint: string | null;
  suite: string;
  total: number;
  passed: number;
  failed: number;
  mtime: number;
  probes: SafetyProbe[];
}

export interface SafetyEvalResults {
  runs: SafetyEvalRun[];
  count: number;
}

export interface FilterInfo {
  name: string;
  category: string;
  purpose: string;
  module: string;
  default_enabled: boolean;
}

export interface FiltersCatalog {
  filters: FilterInfo[];
  count: number;
  categories: string[];
}

export interface ReasoningProblem {
  id: string;
  difficulty: string;
  language: string;
  prompt_preview: string;
  has_tests: boolean;
}

export interface ReasoningProblemSet {
  problems: ReasoningProblem[];
  count: number;
  difficulties: string[];
  languages: string[];
}

export interface VocabToken {
  id: number;
  piece: string;
  is_special: boolean;
}

export interface VocabSearchResult {
  query: string;
  vocab_size: number;
  total_matches: number;
  truncated: boolean;
  tokens: VocabToken[];
  special_tokens: VocabToken[];
}

export interface ScorerConfigEntry {
  name: string;
  enabled: boolean;
  weight: number;
  available: boolean;
  purpose: string;
}

export interface ScoringConfig {
  path: string;
  scorers: ScorerConfigEntry[];
  count: number;
  enabled_count: number;
  curriculum: string | null;
}

export interface RegressionMetric {
  name: string;
  value: number | null;
  baseline: number | null;
  delta: number | null;
  regressed: boolean;
}

export interface RegressionRun {
  name: string;
  path: string;
  checkpoint: string | null;
  mtime: number;
  passed: boolean;
  metrics: RegressionMetric[];
}

export interface RegressionHistory {
  runs: RegressionRun[];
  count: number;
}

export interface DocFile {
  name: string;
  path: string;
  rel: string;
  title: string;
  size_bytes: number;
}

export interface DocsList {
  docs: DocFile[];
  count: number;
}

export interface DocContent {
  path: string;
  content: string;
  truncated: boolean;
}

export interface BacklogItem {
  id: string;
  category: string;
  severity: string;
  status: string;
  date: string | null;
  description: string;
}

export interface BacklogView {
  items: BacklogItem[];
  count: number;
  open_count: number;
  done_count: number;
}

export interface BacklogAppendRequest {
  item_id: string;
  category: string;
  description: string;
  severity?: string;
  status?: 'open' | 'in-progress' | 'done' | 'dropped';
}

export interface ResearchEntry {
  date: string;
  title: string;
  area: string | null;
  source_count: number;
  has_original_idea: boolean;
  summary: string;
}

export interface ResearchLog {
  entries: ResearchEntry[];
  count: number;
}

export interface ResearchLogAppendRequest {
  title: string;
  body: string;
}

export interface TrainingManifest {
  model: string;
  path: string;
  config: string | null;
  dim: number | null;
  n_layers: number | null;
  n_heads: number | null;
  seq_len: number | null;
  batch_size: number | null;
  learning_rate: number | null;
  max_steps: number | null;
  latest_step: number | null;
  created_at: string | null;
  mtime: number;
}

export interface TrainingManifests {
  manifests: TrainingManifest[];
  count: number;
}

export interface LrPoint {
  lr: number;
  loss: number;
}

export interface LrFinderRun {
  name: string;
  path: string;
  config: string | null;
  suggested_lr: number | null;
  min_loss: number | null;
  num_points: number;
  mtime: number;
  points: LrPoint[];
}

export interface LrFinderResults {
  runs: LrFinderRun[];
  count: number;
}

export interface RepoScore {
  repo: string;
  score: number;
  stars: number | null;
  language: string | null;
  license: string | null;
  reason: string | null;
}

export interface RepoScoresResult {
  path: string;
  repos: RepoScore[];
  count: number;
  mtime: number;
}

export interface RunRequest {
  action: string;
  args?: string[] | null;
}

export interface TrainStartRequest {
  config?: string;
  resume?: string | null;
}

export interface InferenceRequest {
  prompt: string;
  checkpoint: string;
  config: string;
  max_tokens?: number;
  temperature?: number;
  top_p?: number;
  top_k?: number;
}

export interface InferenceResult {
  completion: string;
  prompt: string;
  checkpoint: string;
  tokens_generated: number;
  elapsed_s: number;
}

export interface RetrievalHit {
  id: string;
  score: number;
  snippet: string;
  source?: string | null;
}

export interface RetrievalSearchResult {
  query: string;
  exists: boolean;
  total_indexed: number;
  hits: RetrievalHit[];
}

export interface GpuProcess {
  pid: number;
  name: string;
  used_memory_mb: number | null;
}

export interface GpuProcesses {
  available: boolean;
  count: number;
  processes: GpuProcess[];
  restricted: boolean;
}

export interface SpecialistEntry {
  domain: string;
  checkpoint: string;
  config?: string | null;
  keywords?: string[];
  confidence_threshold?: number | null;
  description?: string | null;
}

export interface SpecialistsView {
  path: string;
  exists: boolean;
  count: number;
  specialists: SpecialistEntry[];
}

export interface SpecialistSaveRequest {
  domain: string;
  checkpoint: string;
  keywords?: string[];
  config?: string | null;
  confidence_threshold?: number | null;
  description?: string | null;
}

export interface SpecialistRemoveRequest {
  domain: string;
}

export interface DomainDetectRequest {
  code: string;
  filename?: string;
}

export interface DomainScoreOut {
  domain: string;
  import_matches: number;
  keyword_matches: number;
  raw_score: number;
  confidence: number;
}

export interface RouteDecisionOut {
  domain: string;
  confidence: number;
  margin: number;
  abstained: boolean;
  reason: string;
}

export interface DomainDetectResult {
  top_domain: string;
  scores: DomainScoreOut[];
  routing: RouteDecisionOut;
}

export interface GenStreamChunk {
  delta: string;
  done: boolean;
  error?: string | null;
}

export interface BestOfNRequest {
  prompt: string;
  checkpoint: string;
  config: string;
  num_candidates?: number;
  language?: 'auto' | 'python' | 'typescript';
  max_tokens?: number;
  temperature?: number;
  top_p?: number;
  top_k?: number;
}

export interface BestOfNCandidate {
  completion: string;
  verified: boolean;
  score: number;
}

export interface BestOfNResponse {
  best_completion: string;
  language: string;
  verifier: string;
  solved: boolean;
  candidates_used: number;
  elapsed_s: number;
  candidates: BestOfNCandidate[];
}

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface ChatRequest {
  messages: ChatMessage[];
  checkpoint: string;
  config: string;
  use_chat_template?: boolean;
  max_tokens?: number;
  temperature?: number;
  top_p?: number;
  top_k?: number;
}

export interface FimRequest {
  prefix: string;
  suffix: string;
  checkpoint: string;
  config: string;
  max_tokens?: number;
  temperature?: number;
  top_p?: number;
  top_k?: number;
}

export interface ConfigWriteRequest {
  path: string;
  content: string;
}

export interface ConfigWriteResult {
  ok: boolean;
  path: string;
  bytes_written: number;
}

export interface ApiError {
  error: string;
}

export function isApiError<T>(v: T | ApiError): v is ApiError {
  return (
    typeof v === 'object' &&
    v !== null &&
    !Array.isArray(v) &&
    typeof (v as ApiError).error === 'string'
  );
}

export type JobOrError = Job | ApiError;
export type EvalDetailOrError = EvalDetail | ApiError;
export type LogTailOrError = LogTail | ApiError;
export type FeaturesViewOrError = FeaturesView | ApiError;
export type ReasoningViewOrError = ReasoningView | ApiError;
export type TokenizerInfoOrError = TokenizerInfo | ApiError;
export type CheckpointDetailOrError = CheckpointDetail | ApiError;
export type RouterOverviewOrError = RouterOverview | ApiError;
export type ExportOverviewOrError = ExportOverview | ApiError;
export type MetricsHistoryOrError = MetricsHistory | ApiError;
export type DataSourcesViewOrError = DataSourcesView | ApiError;
export type EvalHistoryViewOrError = EvalHistoryView | ApiError;
export type TokenizeResultOrError = TokenizeResult | ApiError;
export type HealthSummaryOrError = HealthSummary | ApiError;
export type SftPreviewOrError = SftPreview | ApiError;
export type ScriptsCatalogOrError = ScriptsCatalog | ApiError;
export type StorageViewOrError = StorageView | ApiError;
export type CompareResultOrError = CompareResult | ApiError;
export type ModelCardOrError = ModelCard | ApiError;
export type FeatureSetResultOrError = FeatureSetResult | ApiError;
export type ConfigDiffOrError = ConfigDiff | ApiError;
export type SystemInfoOrError = SystemInfo | ApiError;
export type PipelineRunDetailOrError = PipelineRunDetail | ApiError;
export type PipelineDeleteResultOrError = PipelineDeleteResult | ApiError;
export type TokenizerHealthReportOrError = TokenizerHealthReport | ApiError;
export type DataStatsOrError = DataStats | ApiError;
export type CheckpointHealthOrError = CheckpointHealth | ApiError;
export type MemoryStatsOrError = MemoryStats | ApiError;
export type IndexStatsOrError = IndexStats | ApiError;
export type MalwareScanResultOrError = MalwareScanResult | ApiError;
export type EnvCheckReportOrError = EnvCheckReport | ApiError;
export type VramEstimateOrError = VramEstimate | ApiError;
export type ProjectHealthReportOrError = ProjectHealthReport | ApiError;
export type BenchmarkResultsOrError = BenchmarkResults | ApiError;
export type SafetyEvalResultsOrError = SafetyEvalResults | ApiError;
export type FiltersCatalogOrError = FiltersCatalog | ApiError;
export type ReasoningProblemSetOrError = ReasoningProblemSet | ApiError;
export type VocabSearchResultOrError = VocabSearchResult | ApiError;
export type ScoringConfigOrError = ScoringConfig | ApiError;
export type RegressionHistoryOrError = RegressionHistory | ApiError;
export type DocsListOrError = DocsList | ApiError;
export type DocContentOrError = DocContent | ApiError;
export type BacklogViewOrError = BacklogView | ApiError;
export type ResearchLogOrError = ResearchLog | ApiError;
export type TrainingManifestsOrError = TrainingManifests | ApiError;
export type LrFinderResultsOrError = LrFinderResults | ApiError;
export type RepoScoresResultOrError = RepoScoresResult | ApiError;
export type InferenceResultOrError = InferenceResult | ApiError;
export type ConfigWriteResultOrError = ConfigWriteResult | ApiError;
export type SpecialistsViewOrError = SpecialistsView | ApiError;
export type RetrievalSearchResultOrError = RetrievalSearchResult | ApiError;
export type BestOfNResponseOrError = BestOfNResponse | ApiError;
