// Single import surface for the web UI.
// The source of truth is `types.gen.ts`, generated by scripts/gen_ts_types.py
// from src/cola_coder/ui/schemas.py. Hand-written duplicates were removed —
// every type, `JsonValue`, `ApiError`, `isApiError`, and the `<Name>OrError`
// aliases now live in the generated file. Keep importing from `./types`.
export * from './types.gen';
