"""Regression tests for the quality filter (data/quality_filter.py).

This module is the data-quality GATE — it decides which scraped code enters
training — but had NO direct test coverage (only the separate filters/ plugins
were tested). A subtle break here silently poisons the training set.

The headline guard is check_character_diversity's DENOMINATOR CAP: unique chars
are bounded by the charset (~95 for ASCII code), so without the cap a normal
large code file scores unique/total ≈ 0 and would be WRONGLY rejected. These
tests lock that (and the other key checks) so the cap can't be "fixed" away.
"""

from cola_coder.data.quality_filter import (
    FilterMode,
    check_avg_line_length,
    check_character_diversity,
    check_length,
    check_max_line_length,
    check_not_autogenerated,
    check_not_data_file,
    filter_code,
    score_code,
)

_GOOD_PYTHON = '''\
import math


def area_of_circle(radius: float) -> float:
    """Return the area of a circle with the given radius."""
    if radius < 0:
        raise ValueError("radius must be non-negative")
    return math.pi * radius * radius


def factorial(n: int) -> int:
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result
'''


class TestCharacterDiversityCap:
    """The denominator cap is correct and MUST stay — these guard it."""

    def test_large_diverse_code_passes(self):
        # 2000 chars cycling through 90 printable ASCII chars => 90 unique.
        # With the cap: 90/1000 = 0.09 >= 0.05 -> PASS.
        # WITHOUT the cap (the bug an agent proposed): 90/2000 = 0.045 -> REJECT.
        diverse = "".join(chr(33 + (i % 90)) for i in range(2000))
        keep, _ = check_character_diversity(diverse)
        assert keep is True, (
            "Large diverse code was rejected — did someone remove the "
            "denominator cap in check_character_diversity? Unique chars are "
            "bounded by the charset, so the cap is REQUIRED."
        )

    def test_repetitive_large_file_rejected(self):
        # 3000 chars, only 3 unique ({a, b, \\n}) -> 3/1000 = 0.003 -> REJECT.
        repetitive = "ab\n" * 1000
        keep, reason = check_character_diversity(repetitive)
        assert keep is False
        assert "low_diversity" in reason

    def test_single_char_file_rejected(self):
        keep, _ = check_character_diversity("A" * 5000)
        assert keep is False

    def test_short_file_is_not_judged(self):
        keep, _ = check_character_diversity("abc")  # < 100 chars
        assert keep is True

    def test_strict_threshold_is_tighter(self):
        # 60 unique chars over a long file: 60/1000 = 0.06.
        # Passes conservative (>= 0.05) but fails strict (>= 0.08).
        s = "".join(chr(33 + (i % 60)) for i in range(2000))
        assert check_character_diversity(s, min_unique_ratio=0.05)[0] is True
        assert check_character_diversity(s, min_unique_ratio=0.08)[0] is False


class TestIndividualChecks:
    def test_length_rejects_too_short(self):
        assert check_length("x = 1\n")[0] is False  # < 5 lines

    def test_length_accepts_normal(self):
        assert check_length("a\nb\nc\nd\ne\nf\n")[0] is True

    def test_avg_line_length_rejects_minified(self):
        assert check_avg_line_length("x" * 5000 + "\n")[0] is False

    def test_max_line_length_rejects_blob(self):
        assert check_max_line_length("ok\n" + "z" * 1500 + "\n")[0] is False

    def test_autogenerated_marker_rejected(self):
        keep, reason = check_not_autogenerated("// Auto-generated by tool\nx=1\n")
        assert keep is False
        assert "autogenerated" in reason

    def test_normal_header_passes_autogen_check(self):
        assert check_not_autogenerated(_GOOD_PYTHON)[0] is True

    def test_data_file_rejected(self):
        # CSV detection requires avg > 5 commas/line (7+ fields) so it doesn't
        # false-positive on code that happens to use a few commas.
        csv = "a,b,c,d,e,f,g\n" + "\n".join("1,2,3,4,5,6,7" for _ in range(60))
        assert check_not_data_file(csv)[0] is False

    def test_code_with_few_commas_not_flagged_as_data(self):
        # Guard the threshold: ordinary code with commas must NOT be rejected.
        assert check_not_data_file(_GOOD_PYTHON)[0] is True


class TestFilterCodeEndToEnd:
    def test_good_code_passes_conservative(self):
        keep, reason = filter_code(_GOOD_PYTHON, mode=FilterMode.CONSERVATIVE)
        assert keep is True, f"good code rejected: {reason}"

    def test_good_code_passes_strict(self):
        keep, reason = filter_code(
            _GOOD_PYTHON, mode=FilterMode.STRICT, languages=["python"]
        )
        assert keep is True, f"good code rejected in strict: {reason}"

    def test_too_short_rejected(self):
        keep, reason = filter_code("x = 1\n")
        assert keep is False
        assert "too_short" in reason

    def test_autogenerated_rejected(self):
        keep, reason = filter_code(
            "# This file is generated\n" + _GOOD_PYTHON
        )
        assert keep is False
        assert "autogenerated" in reason

    def test_minified_rejected(self):
        keep, reason = filter_code("const x=" + "a" * 3000 + ";\n" * 6)
        assert keep is False


class TestScoreCode:
    def test_good_code_scores_high(self):
        score, breakdown = score_code(_GOOD_PYTHON)
        assert 0.0 <= score <= 1.0
        assert score > 0.6
        assert isinstance(breakdown, dict) and breakdown

    def test_junk_scores_lower_than_good(self):
        good, _ = score_code(_GOOD_PYTHON)
        junk, _ = score_code("A" * 3000 + "\n" * 6)
        assert junk < good
