"""Tests for the manifest provenance system."""

import tempfile
from pathlib import Path

import yaml
import pytest

from cola_coder.manifest import (
    write_data_manifest,
    write_training_manifest,
    read_manifest,
    file_sha256,
)


@pytest.fixture
def tmp_dir():
    """Create a temporary directory for test outputs."""
    with tempfile.TemporaryDirectory() as d:
        yield Path(d)


class TestWriteDataManifest:
    """Tests for write_data_manifest."""

    def test_creates_valid_yaml(self, tmp_dir):
        path = tmp_dir / "test.manifest.yaml"
        write_data_manifest(
            path,
            output_file="train_data.npy",
            output_size_bytes=1_000_000,
            num_chunks=100,
            chunk_size=2048,
            total_tokens=204800,
            dtype="uint16",
            dataset="bigcode/starcoderdata",
            languages=["typescript", "javascript"],
            filter_mode="conservative",
            filter_stats={"total": 1000, "kept": 520},
            tokenizer_path="nonexistent.json",
            vocab_size=32768,
            workers=4,
            batch_size=256,
            max_tokens=500_000,
            wall_time_seconds=60.5,
            throughput_tokens_per_sec=3400.0,
        )
        assert path.exists()
        data = yaml.safe_load(path.read_text())
        assert data["version"] == "1.0"
        assert "created" in data
        assert data["tool"] == "cola-coder/prepare_data.py"

    def test_data_section(self, tmp_dir):
        path = tmp_dir / "test.manifest.yaml"
        write_data_manifest(
            path,
            output_file="train.npy",
            num_chunks=50,
            chunk_size=1024,
            total_tokens=51200,
        )
        data = yaml.safe_load(path.read_text())
        assert data["data"]["output_file"] == "train.npy"
        assert data["data"]["num_chunks"] == 50
        assert data["data"]["chunk_size"] == 1024
        assert data["data"]["total_tokens"] == 51200

    def test_source_section(self, tmp_dir):
        path = tmp_dir / "test.manifest.yaml"
        write_data_manifest(
            path,
            dataset="bigcode/starcoderdata",
            languages=["python", "typescript"],
        )
        data = yaml.safe_load(path.read_text())
        assert data["source"]["dataset"] == "bigcode/starcoderdata"
        assert data["source"]["languages"] == ["python", "typescript"]

    def test_filter_section_with_stats(self, tmp_dir):
        path = tmp_dir / "test.manifest.yaml"
        write_data_manifest(
            path,
            filter_mode="strict",
            filter_stats={
                "total": 10000,
                "kept": 3500,
                "top_rejections": {"too_short": 2000, "autogenerated": 1500},
            },
        )
        data = yaml.safe_load(path.read_text())
        assert data["filter"]["mode"] == "strict"
        assert data["filter"]["total_files_processed"] == 10000
        assert data["filter"]["files_kept"] == 3500
        assert data["filter"]["keep_rate"] == 0.35
        assert data["filter"]["top_rejections"]["too_short"] == 2000

    def test_processing_section(self, tmp_dir):
        path = tmp_dir / "test.manifest.yaml"
        write_data_manifest(
            path,
            workers=8,
            batch_size=128,
            wall_time_seconds=120.7,
            throughput_tokens_per_sec=5000.0,
        )
        data = yaml.safe_load(path.read_text())
        assert data["processing"]["workers"] == 8
        assert data["processing"]["batch_size"] == 128
        assert data["processing"]["wall_time_seconds"] == 120.7

    def test_environment_section(self, tmp_dir):
        path = tmp_dir / "test.manifest.yaml"
        write_data_manifest(path)
        data = yaml.safe_load(path.read_text())
        assert "environment" in data
        assert "platform" in data["environment"]
        assert "python" in data["environment"]
        assert "hostname" in data["environment"]

    def test_tokenizer_sha256(self, tmp_dir):
        # Create a fake tokenizer file
        tok_file = tmp_dir / "tokenizer.json"
        tok_file.write_text('{"test": true}')

        path = tmp_dir / "test.manifest.yaml"
        write_data_manifest(
            path,
            tokenizer_path=str(tok_file),
            vocab_size=32768,
        )
        data = yaml.safe_load(path.read_text())
        assert data["tokenizer"]["vocab_size"] == 32768
        assert len(data["tokenizer"]["sha256"]) == 64  # SHA-256 hex length


class TestWriteTrainingManifest:
    """Tests for write_training_manifest."""

    def test_creates_valid_yaml(self, tmp_dir):
        path = tmp_dir / "training_manifest.yaml"
        write_training_manifest(
            path,
            model_config={"dim": 512, "n_layers": 8, "vocab_size": 32768},
            training_config={"learning_rate": 3e-4, "batch_size": 16},
            step=1000,
            loss=3.05,
            tokens_seen=163840,
            epochs_completed=1.5,
            max_steps=20000,
            loss_history={"step_1000": 3.05},
            checkpoint_path="checkpoints/tiny/step_00001000",
        )
        assert path.exists()
        data = yaml.safe_load(path.read_text())
        assert data["version"] == "1.0"
        assert "created" in data
        assert "updated" in data

    def test_model_section(self, tmp_dir):
        path = tmp_dir / "training_manifest.yaml"
        write_training_manifest(
            path,
            model_config={"dim": 512, "n_layers": 8, "n_heads": 8},
        )
        data = yaml.safe_load(path.read_text())
        assert data["model"]["architecture"] == "decoder-only transformer"
        assert data["model"]["dim"] == 512
        assert data["model"]["n_layers"] == 8

    def test_progress_section(self, tmp_dir):
        path = tmp_dir / "training_manifest.yaml"
        write_training_manifest(
            path,
            step=5000,
            loss=2.5,
            tokens_seen=1638400,
            epochs_completed=3.2,
            max_steps=20000,
            loss_history={"step_1000": 3.0, "step_5000": 2.5},
        )
        data = yaml.safe_load(path.read_text())
        assert data["progress"]["current_step"] == 5000
        assert data["progress"]["tokens_seen"] == 1638400
        assert data["progress"]["epochs_completed"] == 3.2
        assert data["progress"]["current_loss"] == 2.5
        assert data["progress"]["best_loss"] == 2.5
        assert data["progress"]["best_step"] == 5000
        assert data["progress"]["loss_history"]["step_1000"] == 3.0

    def test_updates_existing_manifest(self, tmp_dir):
        path = tmp_dir / "training_manifest.yaml"

        # First write
        write_training_manifest(
            path,
            step=1000,
            loss=3.0,
            loss_history={"step_1000": 3.0},
            checkpoint_path="ckpt/step_1000",
        )
        data1 = yaml.safe_load(path.read_text())
        created = data1["created"]

        # Second write (update)
        write_training_manifest(
            path,
            step=2000,
            loss=2.8,
            loss_history={"step_1000": 3.0, "step_2000": 2.8},
            checkpoint_path="ckpt/step_2000",
        )
        data2 = yaml.safe_load(path.read_text())

        # Created should stay the same
        assert data2["created"] == created
        # Updated timestamp should exist
        assert "updated" in data2
        # Checkpoints should accumulate
        assert len(data2["checkpoints"]) == 2

    def test_tracks_best_loss(self, tmp_dir):
        path = tmp_dir / "training_manifest.yaml"

        write_training_manifest(path, step=1000, loss=3.0)
        write_training_manifest(path, step=2000, loss=2.5)
        write_training_manifest(path, step=3000, loss=2.8)  # Worse than best

        data = yaml.safe_load(path.read_text())
        assert data["progress"]["best_loss"] == 2.5
        assert data["progress"]["best_step"] == 2000

    def test_data_provenance_from_data_manifest(self, tmp_dir):
        # Create a data manifest first
        data_manifest_path = tmp_dir / "train.manifest.yaml"
        write_data_manifest(
            data_manifest_path,
            num_chunks=1000,
            chunk_size=2048,
            total_tokens=2048000,
        )

        # Write training manifest referencing the data manifest
        path = tmp_dir / "training_manifest.yaml"
        write_training_manifest(
            path,
            data_path="data/train.npy",
            data_manifest_path=str(data_manifest_path),
        )
        data = yaml.safe_load(path.read_text())
        assert data["data"]["num_chunks"] == 1000
        assert data["data"]["total_tokens"] == 2048000


class TestReadManifest:
    """Tests for read_manifest."""

    def test_reads_data_manifest(self, tmp_dir):
        path = tmp_dir / "test.manifest.yaml"
        write_data_manifest(path, output_file="test.npy", num_chunks=42)

        result = read_manifest(str(path))
        assert isinstance(result, dict)
        assert result["data"]["num_chunks"] == 42

    def test_reads_training_manifest(self, tmp_dir):
        path = tmp_dir / "training_manifest.yaml"
        write_training_manifest(
            path,
            model_config={"dim": 256},
            step=500,
            loss=4.0,
        )

        result = read_manifest(str(path))
        assert result["model"]["dim"] == 256
        assert result["progress"]["current_step"] == 500

    def test_raises_on_missing_file(self):
        with pytest.raises(FileNotFoundError):
            read_manifest("nonexistent_file.yaml")

    def test_roundtrip(self, tmp_dir):
        """Write a manifest and read it back — all data should survive."""
        path = tmp_dir / "roundtrip.manifest.yaml"
        write_data_manifest(
            path,
            output_file="train.npy",
            output_size_bytes=999,
            num_chunks=10,
            chunk_size=512,
            total_tokens=5120,
            dtype="uint16",
            dataset="test/dataset",
            languages=["python"],
            filter_mode="none",
            workers=2,
            batch_size=32,
        )

        result = read_manifest(str(path))
        assert result["data"]["output_file"] == "train.npy"
        assert result["data"]["total_tokens"] == 5120
        assert result["source"]["languages"] == ["python"]
        assert result["filter"]["mode"] == "none"
        assert result["processing"]["workers"] == 2


class TestFileSha256:
    """Tests for file_sha256 helper."""

    def test_deterministic(self, tmp_dir):
        f = tmp_dir / "test.txt"
        f.write_text("hello world")
        h1 = file_sha256(str(f))
        h2 = file_sha256(str(f))
        assert h1 == h2
        assert len(h1) == 64

    def test_different_content_different_hash(self, tmp_dir):
        f1 = tmp_dir / "a.txt"
        f2 = tmp_dir / "b.txt"
        f1.write_text("hello")
        f2.write_text("world")
        assert file_sha256(str(f1)) != file_sha256(str(f2))
