"""Generate ``webui/src/types.gen.ts`` from the Pydantic models in
``src/cola_coder/ui/schemas.py`` (the single source of truth).

Introspects every UI ``BaseModel`` via ``model_fields`` + ``typing`` and emits
exact 1:1 TypeScript interfaces. Output is deterministic (fixed model order,
declared field order) so ``tests/test_ui_types_generated.py`` can byte-compare
against the committed file as a drift guard.

NEVER hand-edit types.gen.ts — edit schemas.py and run this script.

Usage:
    .venv/Scripts/python.exe scripts/gen_ts_types.py
"""

from __future__ import annotations

import sys
import types as _types
import typing
from pathlib import Path
from typing import Union, get_args, get_origin

# Make the package importable when run as a plain script.
_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "src"))

from pydantic import BaseModel  # noqa: E402
from pydantic.fields import FieldInfo  # noqa: E402

from cola_coder.cli import cli  # noqa: E402
from cola_coder.ui import schemas  # noqa: E402

_OUTPUT_PATH = _ROOT / "webui" / "src" / "types.gen.ts"

_HEADER = (
    "// GENERATED by scripts/gen_ts_types.py from "
    "src/cola_coder/ui/schemas.py — DO NOT EDIT.\n"
)

# Recursive principled open-JSON type, emitted once. Maps schemas.JsonValue.
_JSON_VALUE_BLOCK = (
    "export type JsonValue =\n"
    "  | string\n"
    "  | number\n"
    "  | boolean\n"
    "  | null\n"
    "  | JsonValue[]\n"
    "  | { [key: string]: JsonValue };\n"
)

# Fixed emission order — mirrors webui/src/types.ts so regeneration is stable.
# (ConfigDiffSide / DiskInfo are named sub-objects that types.ts inlined.)
_MODEL_ORDER: list[str] = [
    "TrainingStatus",
    "SystemStatus",
    "Checkpoint",
    "StatusResponse",
    "Dataset",
    "Job",
    "ActionDef",
    "JobLogChunk",
    "SftFile",
    "SftPreview",
    "ScriptInfo",
    "ScriptsCatalog",
    "ScoreSummary",
    "Preview",
    "ConfigFile",
    "ConfigContent",
    "PipelineRun",
    "PipelineStageState",
    "PipelineRunDetail",
    "PipelineDeleteResult",
    "EvalResult",
    "EvalDetail",
    "LogFile",
    "LogTail",
    "FeatureItem",
    "FeatureGroup",
    "FeaturesView",
    "ReasoningSummary",
    "ReasoningView",
    "TokenizerInfo",
    "CheckpointDetail",
    "RouterCheckpoint",
    "RouterOverview",
    "ExportFormat",
    "ExportItem",
    "ExportCheckpoint",
    "ExportOverview",
    "MetricPoint",
    "MetricsHistory",
    "DataSource",
    "DataSourcesView",
    "EvalSnapshot",
    "EvalHistoryView",
    "TokenizeResult",
    "HealthCheck",
    "HealthSummary",
    "StorageEntry",
    "StorageView",
    "CompareDiff",
    "CompareResult",
    "ModelCard",
    "FeatureSetResult",
    "ConfigChange",
    "ConfigDiffSide",
    "ConfigDiff",
    "GpuInfo",
    "DiskInfo",
    "SystemInfo",
    "TokenizerHealthItem",
    "TokenizerHealthReport",
    "WeightTier",
    "DataStats",
    "CheckpointHealth",
    "MemoryEntry",
    "MemoryStats",
    "IndexStats",
    "ThreatInfo",
    "MalwareScanResult",
    "EnvCheckItem",
    "EnvCheckReport",
    "VramComponent",
    "VramEstimate",
    "HealthDimension",
    "ProjectHealthReport",
    "BenchmarkRun",
    "BenchmarkResults",
    "SafetyProbe",
    "SafetyEvalRun",
    "SafetyEvalResults",
    "FilterInfo",
    "FiltersCatalog",
    "ReasoningProblem",
    "ReasoningProblemSet",
    "VocabToken",
    "VocabSearchResult",
    "ScorerConfigEntry",
    "ScoringConfig",
    "RegressionMetric",
    "RegressionRun",
    "RegressionHistory",
    "BacklogItem",
    "BacklogView",
    "ResearchEntry",
    "ResearchLog",
    "TrainingManifest",
    "TrainingManifests",
    "LrPoint",
    "LrFinderRun",
    "LrFinderResults",
    "RepoScore",
    "RepoScoresResult",
    "RunRequest",
    "TrainStartRequest",
]

# Models the frontend treats as ``Model | ApiError`` (mirrors webui/src/api.ts).
# Emitted as ``export type <Name>OrError = <Name> | ApiError;`` aliases so the
# later wave can drop the hand-written unions.
_OR_ERROR: list[str] = [
    "Job",
    "EvalDetail",
    "LogTail",
    "FeaturesView",
    "ReasoningView",
    "TokenizerInfo",
    "CheckpointDetail",
    "RouterOverview",
    "ExportOverview",
    "MetricsHistory",
    "DataSourcesView",
    "EvalHistoryView",
    "TokenizeResult",
    "HealthSummary",
    "SftPreview",
    "ScriptsCatalog",
    "StorageView",
    "CompareResult",
    "ModelCard",
    "FeatureSetResult",
    "ConfigDiff",
    "SystemInfo",
    "PipelineRunDetail",
    "PipelineDeleteResult",
    "TokenizerHealthReport",
    "DataStats",
    "CheckpointHealth",
    "MemoryStats",
    "IndexStats",
    "MalwareScanResult",
    "EnvCheckReport",
    "VramEstimate",
    "ProjectHealthReport",
    "BenchmarkResults",
    "SafetyEvalResults",
    "FiltersCatalog",
    "ReasoningProblemSet",
    "VocabSearchResult",
    "ScoringConfig",
    "RegressionHistory",
    "BacklogView",
    "ResearchLog",
    "TrainingManifests",
    "LrFinderResults",
    "RepoScoresResult",
]


def _is_union(origin: object) -> bool:
    return origin is Union or origin is _types.UnionType


def _is_json_value(annotation: object) -> bool:
    """True if the annotation is exactly the shared ``schemas.JsonValue`` alias."""
    return annotation is schemas.JsonValue


def _ts_for_annotation(annotation: object) -> str:
    """Map a Python type annotation to its TypeScript expression."""
    if _is_json_value(annotation):
        return "JsonValue"

    if annotation is None or annotation is type(None):
        return "null"
    if annotation is str:
        return "string"
    if annotation is bool:
        return "boolean"
    if annotation is int or annotation is float:
        return "number"

    origin = get_origin(annotation)

    if origin is typing.Literal:
        return _ts_for_literal(get_args(annotation))

    if _is_union(origin):
        return _ts_for_union(get_args(annotation))

    if origin in (list, typing.List):  # noqa: UP006 - explicit for clarity
        (inner,) = get_args(annotation)
        return f"{_ts_for_element(inner)}[]"

    if origin in (dict, typing.Dict):  # noqa: UP006
        _key, value = get_args(annotation)
        return f"Record<string, {_ts_for_annotation(value)}>"

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return _interface_name(annotation)

    raise TypeError(f"Unsupported annotation for TS generation: {annotation!r}")


def _ts_for_element(annotation: object) -> str:
    """TS for an array/element position; parenthesize unions so ``X[]`` binds."""
    rendered = _ts_for_annotation(annotation)
    origin = get_origin(annotation)
    if _is_union(origin) and not _is_json_value(annotation):
        return f"({rendered})"
    return rendered


def _ts_for_literal(args: tuple[object, ...]) -> str:
    parts: list[str] = []
    for arg in args:
        if isinstance(arg, bool):
            parts.append("true" if arg else "false")
        elif isinstance(arg, str):
            parts.append(f"'{arg}'")
        elif isinstance(arg, (int, float)):
            parts.append(str(arg))
        else:
            raise TypeError(f"Unsupported Literal member: {arg!r}")
    return " | ".join(parts)


def _ts_for_union(args: tuple[object, ...]) -> str:
    parts: list[str] = []
    for arg in args:
        rendered = _ts_for_annotation(arg)
        if rendered not in parts:
            parts.append(rendered)
    return " | ".join(parts)


def _interface_name(model: type[BaseModel]) -> str:
    """The TS interface name for a model (ErrorResponse → ApiError)."""
    if model is schemas.ErrorResponse:
        return "ApiError"
    return model.__name__


def _field_is_optional_marker(info: FieldInfo) -> bool:
    """True if the TS field should be marked ``name?:`` (has a default → may be
    absent in the response).
    """
    return not info.is_required()


def _emit_interface(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for field_name, info in model.model_fields.items():
        ts_type = _ts_for_annotation(info.annotation)
        optional = "?" if _field_is_optional_marker(info) else ""
        lines.append(f"  {field_name}{optional}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def build_ts() -> str:
    """Build the full deterministic types.gen.ts content as a string."""
    blocks: list[str] = [_HEADER.rstrip("\n"), "", _JSON_VALUE_BLOCK.rstrip("\n"), ""]

    for name in _MODEL_ORDER:
        model = getattr(schemas, name)
        blocks.append(_emit_interface(model))
        blocks.append("")

    # ApiError (from ErrorResponse) + type guard, mirroring types.ts.
    blocks.append(_emit_interface(schemas.ErrorResponse).replace(
        "export interface ErrorResponse {", "export interface ApiError {"
    ))
    blocks.append("")
    blocks.append(
        "export function isApiError<T>(v: T | ApiError): v is ApiError {\n"
        "  return (\n"
        "    typeof v === 'object' &&\n"
        "    v !== null &&\n"
        "    !Array.isArray(v) &&\n"
        "    typeof (v as ApiError).error === 'string'\n"
        "  );\n"
        "}"
    )
    blocks.append("")

    for name in _OR_ERROR:
        blocks.append(f"export type {name}OrError = {name} | ApiError;")
    blocks.append("")

    return "\n".join(blocks)


def main() -> int:
    content = build_ts()
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(content, encoding="utf-8", newline="\n")
    n_interfaces = len(_MODEL_ORDER) + 1  # + ApiError
    cli.success(f"Wrote {_OUTPUT_PATH} ({n_interfaces} interfaces, "
                f"{len(_OR_ERROR)} OrError aliases).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
