"""Data mixing optimization for training.

Implements approaches to find optimal data source proportions:

1. Presets: Expert-defined ratios based on domain knowledge
2. Inverse-Loss: Track per-source validation loss, increase weight of high-loss sources
3. Grid Search: Try N mixing ratios with small proxy model, pick best (stub)

For a small project, approach 1 (presets) or 2 (inverse-loss reweighting) is most
practical. Grid search requires training infrastructure and is provided as a stub.

Think of this like load balancer weights in a microservice architecture:
you want to route more traffic (training data) to the services (domains)
that are underperforming, not the ones already doing fine.

Usage:
    from cola_coder.data.mixing import MixingConfig, MIXING_PRESETS

    # Use a preset
    config = MixingConfig.from_preset("typescript_focused")
    print(config.sources)
    # {"typescript": 0.50, "javascript": 0.25, "python": 0.15, "other": 0.10}

    # Use inverse-loss reweighting
    optimizer = MixingOptimizer()
    config = optimizer.suggest_proportions({
        "typescript": 2.8,  # high loss = model struggles here
        "javascript": 2.1,
        "python": 1.9,      # low loss = model is already decent
    })
    # typescript gets higher weight since it has the highest loss
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def write_weighted_data_sources(
    ratios: dict[str, float],
    out_path: str | Path,
    base_path: str | Path = "configs/data_sources.yaml",
) -> Path:
    """Write a derived data_sources.yaml with per-source weights from `ratios`.

    `scripts/collect_data.py` reads `sources.{code,text,math}.weight` to decide
    the collection mix. This builds a derived config from `base_path` (preserving
    each source's dataset/languages/length settings) with the weights overridden,
    so the "Prepare Mixed Data" menu's ratio choice actually controls the mix.
    A source with weight 0 is disabled so collect_data skips it entirely.

    Args:
        ratios: e.g. {"code": 0.7, "text": 0.15, "math": 0.15}.
        out_path: Where to write the derived config.
        base_path: Base data_sources.yaml to copy non-weight fields from.

    Returns:
        The path the derived config was written to.
    """
    import yaml

    base = yaml.safe_load(Path(base_path).read_text(encoding="utf-8")) or {}
    sources = base.setdefault("sources", {})
    for name, weight in ratios.items():
        src = sources.setdefault(name, {})
        src["weight"] = float(weight)
        src["enabled"] = float(weight) > 0.0

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Auto-generated by the Prepare Mixed Data menu — edits will be "
        "overwritten.\n" + yaml.safe_dump(base, sort_keys=False),
        encoding="utf-8",
    )
    return out


# ---------------------------------------------------------------------------
# MixingConfig — describes a set of source proportions
# ---------------------------------------------------------------------------


@dataclass
class MixingConfig:
    """Define mixing proportions for data sources.

    Like a TypeScript Record<string, number> — maps source names to their
    weight in the training mix. Weights are relative and get normalized
    to sum to 1.0 before use.

    Attributes:
        sources: Mapping of source name to weight.
            e.g., {"typescript": 0.5, "javascript": 0.2, "python": 0.3}
    """

    sources: dict[str, float]

    def __post_init__(self):
        if not self.sources:
            raise ValueError("MixingConfig requires at least one source")
        for name, weight in self.sources.items():
            if weight < 0:
                raise ValueError(
                    f"Weight for {name!r} must be non-negative, got {weight}"
                )
        if sum(self.sources.values()) <= 0:
            raise ValueError("Weights must sum to a positive number")

    @classmethod
    def from_preset(cls, preset: str) -> MixingConfig:
        """Load a preset mixing config by name.

        Available presets:
            - "typescript_focused": 50% TS, 25% JS, 15% Python, 10% other
            - "balanced_code": Distributed across 6 languages
            - "quality_tiers": Weight by data quality level
            - "equal": Equal weights for all languages in the preset

        Raises:
            KeyError: If the preset name is not found.
        """
        if preset not in MIXING_PRESETS:
            available = ", ".join(sorted(MIXING_PRESETS.keys()))
            raise KeyError(
                f"Unknown mixing preset {preset!r}. "
                f"Available presets: {available}"
            )
        return MIXING_PRESETS[preset]

    def normalize(self) -> MixingConfig:
        """Return a new MixingConfig with weights normalized to sum to 1.0.

        Like Array.map(x => x / total) — rescales all weights proportionally
        so they sum to exactly 1.0.
        """
        total = sum(self.sources.values())
        if total <= 0:
            raise ValueError("Cannot normalize: weights sum to zero or negative")
        normalized = {k: v / total for k, v in self.sources.items()}
        return MixingConfig(sources=normalized)

    def is_normalized(self, tol: float = 1e-6) -> bool:
        """Check if weights already sum to ~1.0."""
        return abs(sum(self.sources.values()) - 1.0) < tol

    def to_weight_list(self, source_names: list[str]) -> list[float]:
        """Convert to an ordered list of weights matching the given source names.

        Sources not present in this config get weight 0.0.
        Useful for passing to DatasetCombiner or MixedSource which expect lists.

        Args:
            source_names: Ordered list of source names.

        Returns:
            List of weights in the same order, normalized to sum to 1.0.
        """
        raw = [self.sources.get(name, 0.0) for name in source_names]
        total = sum(raw)
        if total <= 0:
            # None of the requested sources are in this config
            # Fall back to equal weights
            return [1.0 / len(source_names)] * len(source_names)
        return [w / total for w in raw]

    def describe(self) -> str:
        """Human-readable description of the mixing proportions."""
        normalized = self.normalize()
        parts = []
        for name, weight in sorted(
            normalized.sources.items(), key=lambda x: -x[1]
        ):
            parts.append(f"{name}: {weight:.0%}")
        return ", ".join(parts)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a plain dict (for YAML/JSON config files)."""
        return {"sources": dict(self.sources)}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> MixingConfig:
        """Deserialize from a plain dict."""
        return cls(sources=data["sources"])


# ---------------------------------------------------------------------------
# Presets — expert-defined mixing ratios
# ---------------------------------------------------------------------------

MIXING_PRESETS: dict[str, MixingConfig] = {
    "typescript_focused": MixingConfig(
        sources={
            "typescript": 0.50,
            "javascript": 0.25,
            "python": 0.15,
            "other": 0.10,
        }
    ),
    "balanced_code": MixingConfig(
        sources={
            "typescript": 0.25,
            "javascript": 0.15,
            "python": 0.30,
            "java": 0.15,
            "go": 0.10,
            "rust": 0.05,
        }
    ),
    "quality_tiers": MixingConfig(
        sources={
            "verified": 0.30,
            "tested": 0.25,
            "filtered": 0.30,
            "raw": 0.15,
        }
    ),
    "equal": MixingConfig(
        sources={
            "typescript": 1.0 / 3,
            "javascript": 1.0 / 3,
            "python": 1.0 / 3,
        }
    ),
}


# ---------------------------------------------------------------------------
# PerSourceTracker — track validation loss per data source
# ---------------------------------------------------------------------------


class PerSourceTracker:
    """Track validation loss per data source during training.

    After each validation step, records the loss broken down by which source
    each validation example came from. This enables dynamic reweighting
    during training.

    Like a per-route error rate tracker in a web app — you want to know
    which route is failing the most so you can prioritize fixing it.

    Usage:
        tracker = PerSourceTracker()

        # During validation
        for batch in val_loader:
            loss = model(batch)
            source = batch.metadata["source"]
            tracker.record(source, loss.item())

        # After validation
        weights = tracker.get_weights(method="inverse_loss")
        # {"typescript": 0.40, "python": 0.35, "javascript": 0.25}
    """

    def __init__(self):
        self.source_losses: dict[str, list[float]] = {}

    def record(self, source: str, loss: float) -> None:
        """Record a validation loss for a given source.

        Args:
            source: Name of the data source (e.g., "typescript", "python").
            loss: The loss value for this example/batch.
        """
        if source not in self.source_losses:
            self.source_losses[source] = []
        self.source_losses[source].append(loss)

    def mean_losses(self) -> dict[str, float]:
        """Compute mean loss per source.

        Returns:
            Dict mapping source name to its mean validation loss.
        """
        return {
            source: sum(losses) / len(losses)
            for source, losses in self.source_losses.items()
            if losses
        }

    def get_weights(self, method: str = "inverse_loss") -> dict[str, float]:
        """Compute mixing weights based on tracked losses.

        Args:
            method: Weighting method. One of:
                - "inverse_loss": Higher loss sources get proportionally more
                  weight. weight_i = loss_i / sum(losses). Simple and effective.
                - "softmax": Use softmax of losses for smoother weighting.
                  Prevents extreme weights when one source has much higher loss.
                - "equal": Ignore losses, return equal weights.

        Returns:
            Dict mapping source name to its computed weight (sums to 1.0).

        Raises:
            ValueError: If no losses have been recorded or unknown method.
        """
        means = self.mean_losses()
        if not means:
            raise ValueError("No losses recorded yet")

        if method == "equal":
            n = len(means)
            return {source: 1.0 / n for source in means}

        elif method == "inverse_loss":
            # Higher loss = higher weight (model needs more exposure)
            total = sum(means.values())
            if total <= 0:
                return {source: 1.0 / len(means) for source in means}
            return {source: loss / total for source, loss in means.items()}

        elif method == "softmax":
            # Softmax of losses — smoother than raw proportional
            # Subtract max for numerical stability
            max_loss = max(means.values())
            exp_vals = {
                source: math.exp(loss - max_loss)
                for source, loss in means.items()
            }
            total = sum(exp_vals.values())
            return {source: val / total for source, val in exp_vals.items()}

        else:
            raise ValueError(
                f"Unknown weighting method {method!r}. "
                f"Use 'inverse_loss', 'softmax', or 'equal'."
            )

    def reset(self) -> None:
        """Clear all recorded losses."""
        self.source_losses.clear()

    def summary(self) -> str:
        """Human-readable summary of per-source losses and suggested weights."""
        means = self.mean_losses()
        if not means:
            return "No losses recorded yet."

        lines = ["Per-source validation losses:"]
        for source, loss in sorted(means.items(), key=lambda x: -x[1]):
            count = len(self.source_losses[source])
            lines.append(f"  {source}: {loss:.4f} (n={count})")

        weights = self.get_weights(method="inverse_loss")
        lines.append("\nSuggested weights (inverse_loss):")
        for source, weight in sorted(weights.items(), key=lambda x: -x[1]):
            lines.append(f"  {source}: {weight:.2%}")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# MixingOptimizer — find optimal mixing proportions
# ---------------------------------------------------------------------------


class MixingOptimizer:
    """Find optimal data mixing proportions.

    Two approaches implemented:

    1. suggest_proportions(): Given per-source validation losses, suggest
       new proportions using inverse-loss reweighting (simplified DoReMi).
       Cheap and effective for iterative refinement.

    2. grid_search(): Full grid search with proxy training. Define candidate
       ratios, train a tiny model for each, pick the best. More principled
       but expensive. Currently a stub that returns the preset ratios.

    Think of it like A/B testing for data proportions:
    - suggest_proportions = quick heuristic (like using error rates to route traffic)
    - grid_search = full experiment (like running actual A/B tests)

    Args:
        eval_steps: Number of training steps per candidate in grid search.
        candidates: Number of candidate ratios to try in grid search.
    """

    def __init__(self, eval_steps: int = 500, candidates: int = 10):
        self.eval_steps = eval_steps
        self.candidates = candidates

    def suggest_proportions(
        self,
        source_losses: dict[str, float],
        method: str = "inverse_loss",
        temperature: float = 1.0,
    ) -> MixingConfig:
        """Suggest proportions based on per-source validation loss.

        Higher loss sources get more weight (model needs more exposure).
        This is a simplified DoReMi approach without the reference model.

        Args:
            source_losses: Dict mapping source name to its validation loss.
                e.g., {"typescript": 2.8, "javascript": 2.1, "python": 1.9}
            method: Weighting method ("inverse_loss" or "softmax").
            temperature: Temperature for softmax method. Higher = more uniform.
                Ignored for inverse_loss method.

        Returns:
            MixingConfig with suggested proportions (normalized to sum to 1.0).
        """
        if not source_losses:
            raise ValueError("source_losses must not be empty")

        if method == "inverse_loss":
            total = sum(source_losses.values())
            if total <= 0:
                n = len(source_losses)
                weights = {s: 1.0 / n for s in source_losses}
            else:
                weights = {s: loss / total for s, loss in source_losses.items()}

        elif method == "softmax":
            # Apply temperature scaling then softmax
            max_loss = max(source_losses.values())
            exp_vals = {
                s: math.exp((loss - max_loss) / temperature)
                for s, loss in source_losses.items()
            }
            total = sum(exp_vals.values())
            weights = {s: v / total for s, v in exp_vals.items()}

        else:
            raise ValueError(f"Unknown method {method!r}")

        logger.info(
            "Suggested mixing proportions (%s): %s",
            method,
            {s: f"{w:.2%}" for s, w in weights.items()},
        )

        return MixingConfig(sources=weights)

    def grid_search(
        self,
        sources: dict[str, str],
        eval_data: str,
    ) -> MixingConfig:
        """Full grid search with proxy training.

        This is a stub — implementing it requires the full training loop.
        In a real implementation, this would:
        1. Generate `self.candidates` candidate mixing ratios
        2. For each ratio, create a DatasetCombiner with those weights
        3. Train a tiny proxy model for `self.eval_steps` steps
        4. Measure validation loss on eval_data
        5. Return the ratio with the lowest validation loss

        Args:
            sources: Dict mapping source name to path to data directory.
                e.g., {"typescript": "data/processed/train_ts.npy"}
            eval_data: Path to evaluation dataset.

        Returns:
            MixingConfig with the best proportions found.

        Raises:
            NotImplementedError: Always (this is a stub).
        """
        raise NotImplementedError(
            "Grid search requires training infrastructure. "
            "Use suggest_proportions() with per-source validation losses "
            "for a lightweight alternative, or use a preset from MIXING_PRESETS."
        )

    def generate_candidates(
        self,
        source_names: list[str],
        n: int | None = None,
    ) -> list[MixingConfig]:
        """Generate candidate mixing ratios for grid search.

        Creates a spread of mixing ratios using a simplex grid. Useful if
        you want to implement your own grid search loop.

        For 2 sources: generates n points along [0,1] for the first source.
        For 3+ sources: generates a coarse grid on the probability simplex.

        Args:
            source_names: List of source names.
            n: Number of candidates to generate. Defaults to self.candidates.

        Returns:
            List of MixingConfig objects, each representing one candidate ratio.
        """
        n = n or self.candidates
        k = len(source_names)

        if k == 0:
            raise ValueError("Need at least one source")

        if k == 1:
            return [MixingConfig(sources={source_names[0]: 1.0})]

        if k == 2:
            # Simple linear sweep
            configs = []
            for i in range(n):
                w1 = (i + 1) / (n + 1)  # Avoid 0.0 and 1.0 extremes
                w2 = 1.0 - w1
                configs.append(
                    MixingConfig(
                        sources={source_names[0]: w1, source_names[1]: w2}
                    )
                )
            return configs

        # For 3+ sources: generate random points on the simplex
        # (uniform grid on the simplex is combinatorially expensive)
        import random

        rng = random.Random(42)
        configs = []
        for _ in range(n):
            # Dirichlet-like: generate k exponentials, normalize
            raw = [rng.expovariate(1.0) for _ in range(k)]
            total = sum(raw)
            weights = {
                source_names[i]: raw[i] / total for i in range(k)
            }
            configs.append(MixingConfig(sources=weights))

        return configs
