"""Data quality filtering for code training data.

Filters out low-quality code files before they enter the training pipeline.
This runs between the download step and the tokenization step:

    Stream from HuggingFace → Quality Filter → Tokenize → Train

Two modes:

    CONSERVATIVE (default, --filter):
        Only rejects code that is clearly bad. If it can't determine quality
        (e.g., language not supported for parsing), it passes the file through.
        You lose nothing by using it — it either improves your data or does nothing.
        Typical rejection rate: 40-50% on raw GitHub data (StarCoderData).
        This sounds high, but raw GitHub repos contain huge amounts of noise:
        tiny boilerplate files, auto-generated code, data dumps, minified
        bundles, and syntax-broken files. The StarCoder paper itself filters
        out ~50% of raw data. Each individual check is generous — the
        cumulative effect of 10 checks on millions of files adds up.

    STRICT (--filter-strict):
        Aggressively filters for high-quality code only. Tighter thresholds on
        every check, plus additional checks for code style, naming conventions,
        and structural quality. Rejects anything that isn't clearly GOOD rather
        than just filtering out clearly BAD. Typical rejection rate: 60-75%.
        Use this when you have more data than you need and want to maximize
        quality per token (e.g., TypeScript-only training with plenty of data).

Every filter function returns (keep: bool, reason: str). The reason is logged
so you can see what's being filtered and adjust thresholds.
"""

import ast
import os
import re
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass, field
from enum import Enum
from typing import Iterator


class FilterMode(Enum):
    """Which filtering strictness to use."""
    CONSERVATIVE = "conservative"
    STRICT = "strict"


@dataclass
class FilterStats:
    """Tracks how many files were kept vs rejected, and why."""

    total: int = 0
    kept: int = 0
    rejected: int = 0
    reasons: dict[str, int] = field(default_factory=dict)

    def record(self, kept: bool, reason: str = ""):
        self.total += 1
        if kept:
            self.kept += 1
        else:
            self.rejected += 1
            self.reasons[reason] = self.reasons.get(reason, 0) + 1

    def summary(self) -> str:
        lines = [
            f"Quality filter results:",
            f"  Total files:    {self.total:,}",
            f"  Kept:           {self.kept:,} ({self.kept / max(self.total, 1) * 100:.1f}%)",
            f"  Rejected:       {self.rejected:,} ({self.rejected / max(self.total, 1) * 100:.1f}%)",
        ]
        if self.reasons:
            lines.append("  Rejection reasons:")
            for reason, count in sorted(self.reasons.items(), key=lambda x: -x[1]):
                lines.append(f"    {reason}: {count:,}")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Individual filter functions
# Each returns (keep, reason). keep=True means the file passes.
# ---------------------------------------------------------------------------

def check_length(content: str, min_lines: int = 5, max_lines: int = 10000) -> tuple[bool, str]:
    """Reject files that are too short or too long.

    Very short files (< 5 lines) are usually empty boilerplate or configs.
    Very long files (> 10K lines) are often auto-generated or bundled.
    """
    line_count = content.count("\n") + 1
    if line_count < min_lines:
        return False, f"too_short ({line_count} lines)"
    if line_count > max_lines:
        return False, f"too_long ({line_count} lines)"
    return True, ""


def check_avg_line_length(content: str, max_avg: int = 200) -> tuple[bool, str]:
    """Reject files with extremely long average line length.

    Minified code (JS/CSS bundles) has very long lines. Normal code
    averages 30-60 characters per line. If the average exceeds 200,
    it's almost certainly minified or auto-generated.
    """
    lines = content.split("\n")
    if not lines:
        return False, "empty"
    avg_len = sum(len(line) for line in lines) / len(lines)
    if avg_len > max_avg:
        return False, f"minified (avg line {avg_len:.0f} chars)"
    return True, ""


def check_max_line_length(content: str, max_len: int = 1000) -> tuple[bool, str]:
    """Reject files with any single extremely long line.

    A single line over 1000 chars is a strong signal of minified/generated code,
    base64 blobs, or embedded data.
    """
    for line in content.split("\n"):
        if len(line) > max_len:
            return False, f"long_line ({len(line)} chars)"
    return True, ""


def check_not_autogenerated(content: str) -> tuple[bool, str]:
    """Reject files that appear to be auto-generated.

    Checks for common auto-generation markers in the first 10 lines.
    """
    # Only check the header — auto-gen comments are always at the top
    header = "\n".join(content.split("\n")[:10]).lower()

    markers = [
        "auto-generated",
        "autogenerated",
        "automatically generated",
        "do not edit",
        "do not modify",
        "generated by",
        "generated from",
        "this file is generated",
        "machine generated",
        "code generated by",
        # Common generators
        "generated by the protocol buffer compiler",
        "generated by django",
        "generated by swagger",
        "generated by openapi",
    ]

    for marker in markers:
        if marker in header:
            return False, f"autogenerated ({marker})"

    return True, ""


def check_not_data_file(content: str) -> tuple[bool, str]:
    """Reject files that are mostly data rather than code.

    Data files (JSON dumps, CSV, SQL dumps, hex dumps) are common in repos
    but don't teach the model useful code patterns.
    """
    lines = content.split("\n")
    if not lines:
        return False, "empty"

    # Sample first 50 lines to check patterns
    sample = lines[:50]
    sample_text = "\n".join(sample)

    # Check for JSON array/object dumps (many lines starting with { or [)
    brace_lines = sum(1 for l in sample if l.strip().startswith(("{", "[", "]", "}")))
    if len(sample) > 10 and brace_lines / len(sample) > 0.8:
        return False, "data_file (JSON-like)"

    # Check for hex dumps or base64 blocks
    hex_pattern = re.compile(r"^[0-9a-fA-F\s]{40,}$")
    hex_lines = sum(1 for l in sample if hex_pattern.match(l.strip()))
    if len(sample) > 10 and hex_lines / len(sample) > 0.5:
        return False, "data_file (hex/binary)"

    # Check for CSV-like data (many lines with same number of commas)
    if len(sample) > 10:
        comma_counts = [l.count(",") for l in sample if l.strip()]
        if comma_counts and min(comma_counts) > 3:
            # Many commas and consistent count → probably CSV
            avg = sum(comma_counts) / len(comma_counts)
            variance = sum((c - avg) ** 2 for c in comma_counts) / len(comma_counts)
            if variance < 2.0 and avg > 5:
                return False, "data_file (CSV-like)"

    return True, ""


def check_not_test_heavy(content: str, max_test_ratio: float = 0.9) -> tuple[bool, str]:
    """Allow test files but reject files that are purely assertion dumps.

    Normal test files are fine training data. But some repos contain
    auto-generated test files with thousands of assert lines and no
    real logic — these aren't useful.
    """
    lines = [l.strip() for l in content.split("\n") if l.strip()]
    if len(lines) < 20:
        return True, ""  # Too short to judge

    assert_lines = sum(
        1 for l in lines
        if l.startswith("assert") or l.startswith("self.assert") or l.startswith("expect(")
    )
    ratio = assert_lines / len(lines)
    if ratio > max_test_ratio:
        return False, f"assertion_dump ({ratio:.0%} assert lines)"

    return True, ""


def check_python_parseable(content: str) -> tuple[bool, str]:
    """For Python files: reject if the code doesn't parse.

    If Python's own parser rejects the file, the code has syntax errors.
    The model shouldn't learn from broken code.

    Only applies to files that look like Python (checked by heuristics).
    Non-Python files always pass this check.
    """
    # Only attempt parsing if it looks like Python
    if not _looks_like_python(content):
        return True, ""  # Not Python — pass through

    try:
        ast.parse(content)
        return True, ""
    except SyntaxError:
        return False, "python_syntax_error"


def check_js_ts_parseable(content: str) -> tuple[bool, str]:
    """For JS/TS files: basic syntax sanity check.

    We can't fully parse JS/TS without a real parser (which would be a heavy
    dependency). Instead, check for basic structural issues:
    - Unbalanced braces
    - Obvious truncation

    Non-JS/TS files always pass this check.
    """
    if not _looks_like_js_ts(content):
        return True, ""  # Not JS/TS — pass through

    # Check brace balance (rough check — doesn't handle strings/comments)
    open_braces = content.count("{")
    close_braces = content.count("}")
    imbalance = abs(open_braces - close_braces)

    # Allow small imbalance (template literals, regex, etc. can confuse counting)
    if imbalance > 5 and imbalance / max(open_braces, 1) > 0.2:
        return False, f"js_brace_imbalance ({open_braces} open, {close_braces} close)"

    return True, ""


def check_character_diversity(content: str, min_unique_ratio: float = 0.05) -> tuple[bool, str]:
    """Reject files with very low character diversity.

    Files that are mostly one repeated character or pattern are not useful.
    Normal code uses at least 30-40 unique characters.
    """
    if len(content) < 100:
        return True, ""  # Too short to judge

    unique_chars = len(set(content))
    total_chars = len(content)
    ratio = unique_chars / min(total_chars, 1000)  # Cap denominator for long files

    if ratio < min_unique_ratio:
        return False, f"low_diversity ({unique_chars} unique chars)"

    return True, ""


def check_comment_ratio(content: str, max_comment_ratio: float = 0.85) -> tuple[bool, str]:
    """Reject files that are almost entirely comments.

    License files, documentation headers, and comment-only files
    don't help the model learn code patterns.
    """
    lines = [l.strip() for l in content.split("\n") if l.strip()]
    if len(lines) < 10:
        return True, ""  # Too short to judge

    comment_lines = sum(
        1 for l in lines
        if l.startswith("#") or l.startswith("//") or l.startswith("/*")
        or l.startswith("*") or l.startswith("'''") or l.startswith('"""')
    )
    ratio = comment_lines / len(lines)
    if ratio > max_comment_ratio:
        return False, f"mostly_comments ({ratio:.0%})"

    return True, ""


# ---------------------------------------------------------------------------
# STRICT-ONLY checks
# These only run in strict mode. They reject code that is mediocre,
# not just code that is clearly broken.
# ---------------------------------------------------------------------------

def check_has_functions_or_classes(content: str, min_definitions: int = 1) -> tuple[bool, str]:
    """Reject files with no function or class definitions.

    Top-level scripts with no structure (just loose statements) are
    typically low quality. Good code is organized into functions/classes.
    """
    lines = content.split("\n")
    definition_patterns = [
        "def ", "class ", "function ", "const ", "let ", "export ",
        "async function", "interface ", "type ", "enum ",
    ]
    definitions = sum(
        1 for l in lines
        for pat in definition_patterns
        if pat in l and not l.strip().startswith(("#", "//", "*"))
    )
    if definitions < min_definitions:
        return False, f"no_structure ({definitions} definitions)"
    return True, ""


def check_naming_quality(content: str, min_avg_name_len: float = 3.0) -> tuple[bool, str]:
    """Reject files with very short variable/function names.

    Code full of single-letter variables (a, b, x, i everywhere) is
    typically throwaway/scratch code. Good code uses descriptive names.

    We only check identifiers that appear in assignments and function defs,
    not loop variables (i, j, k are fine in for loops).
    """
    # Extract names from assignments and function definitions
    # This is a rough heuristic — not a full parse
    name_pattern = re.compile(
        r'(?:def |function |const |let |var |export (?:const |let |function )?)([a-zA-Z_]\w*)'
    )
    names = name_pattern.findall(content[:10000])  # Sample first 10K chars

    if len(names) < 5:
        return True, ""  # Not enough names to judge

    # Filter out common short names that are acceptable
    acceptable_short = {"i", "j", "k", "n", "x", "y", "e", "fn", "cb", "db", "id", "ok"}
    meaningful_names = [n for n in names if n.lower() not in acceptable_short]

    if not meaningful_names:
        return True, ""

    avg_len = sum(len(n) for n in meaningful_names) / len(meaningful_names)
    if avg_len < min_avg_name_len:
        return False, f"short_names (avg {avg_len:.1f} chars)"

    return True, ""


def check_code_to_blank_ratio(content: str, min_code_ratio: float = 0.5) -> tuple[bool, str]:
    """Reject files that are mostly blank lines.

    Some files are padded with excessive whitespace. In strict mode,
    at least 50% of lines should have actual content.
    """
    lines = content.split("\n")
    if len(lines) < 10:
        return True, ""

    non_blank = sum(1 for l in lines if l.strip())
    ratio = non_blank / len(lines)
    if ratio < min_code_ratio:
        return False, f"too_sparse ({ratio:.0%} non-blank)"

    return True, ""


def check_no_obvious_copy_paste(content: str, max_duplicate_ratio: float = 0.3) -> tuple[bool, str]:
    """Reject files with heavy internal duplication.

    Files where the same block of code is copy-pasted many times
    (common in auto-generated tests or boilerplate) aren't useful
    training data — the model just memorizes the repeated block.
    """
    lines = [l.strip() for l in content.split("\n") if l.strip() and len(l.strip()) > 10]
    if len(lines) < 20:
        return True, ""

    # Count how many lines appear more than once
    from collections import Counter
    counts = Counter(lines)
    duplicate_lines = sum(count - 1 for count in counts.values() if count > 1)
    ratio = duplicate_lines / len(lines)

    if ratio > max_duplicate_ratio:
        return False, f"internal_duplication ({ratio:.0%} duplicate lines)"

    return True, ""


def check_has_some_documentation(content: str) -> tuple[bool, str]:
    """In strict mode, prefer files that have at least SOME documentation.

    Not requiring full JSDoc on every function — just evidence that
    someone cared enough to write a comment or docstring somewhere.
    """
    doc_indicators = ['"""', "'''", "/**", "* @", "# ", "// "]
    lines = content.split("\n")

    doc_lines = sum(
        1 for l in lines
        if any(ind in l for ind in doc_indicators)
    )

    # Require at least 1 documentation line per 50 lines of code
    if len(lines) > 50 and doc_lines == 0:
        return False, "no_documentation"

    return True, ""


def check_no_hardcoded_secrets(content: str) -> tuple[bool, str]:
    """Reject files that appear to contain hardcoded secrets.

    API keys, passwords, tokens left in code are both a security issue
    and low-quality training data (the model might learn to reproduce them).
    """
    secret_patterns = [
        re.compile(r'(?:api[_-]?key|apikey)\s*[:=]\s*["\'][a-zA-Z0-9]{20,}', re.IGNORECASE),
        re.compile(r'(?:password|passwd|pwd)\s*[:=]\s*["\'][^"\']{8,}', re.IGNORECASE),
        re.compile(r'(?:secret|token)\s*[:=]\s*["\'][a-zA-Z0-9]{20,}', re.IGNORECASE),
        re.compile(r'(?:aws_access_key_id|aws_secret_access_key)\s*[:=]', re.IGNORECASE),
        re.compile(r'-----BEGIN (?:RSA |EC )?PRIVATE KEY-----'),
        re.compile(r'sk-[a-zA-Z0-9]{32,}'),  # OpenAI-style keys
        re.compile(r'ghp_[a-zA-Z0-9]{36}'),  # GitHub personal access tokens
    ]

    # Only check first 5K chars — secrets are usually near the top
    sample = content[:5000]
    for pattern in secret_patterns:
        if pattern.search(sample):
            return False, "hardcoded_secret"

    return True, ""


# ---------------------------------------------------------------------------
# Heuristics for language detection
# ---------------------------------------------------------------------------

def _looks_like_python(content: str) -> bool:
    """Quick heuristic: does this content look like Python?

    Must use Python-SPECIFIC indicators to avoid false positives on TS/JS.
    'import' and 'class' exist in both languages, so they're not useful
    as Python indicators. Instead use things only Python has: 'def ',
    'self.', 'if __name__', '#!' + python, indentation-based blocks, etc.

    Also: if the file looks like JS/TS, skip Python parsing even if it
    has some Python-like keywords. This prevents rejecting valid TS/JS
    files that happen to use 'import' + 'class'.
    """
    header = content[:2000]

    # If it looks like JS/TS, it's NOT Python — even if it has 'def' or 'self'
    js_ts_signals = ["const ", "let ", "=> ", "require(", "export ", "interface ", "type "]
    if sum(1 for s in js_ts_signals if s in header) >= 2:
        return False

    # Python-specific indicators (not shared with JS/TS)
    py_indicators = [
        "def ",          # function definitions (JS uses 'function')
        "self.",         # instance references (JS uses 'this.')
        "if __name__",   # Python entry point pattern
        "elif ",         # Python-only keyword (JS uses 'else if')
        "except ",       # Python-only (JS uses 'catch')
        "print(",        # common in Python (less so in modern JS)
        "#!/usr/bin",    # shebang lines
    ]
    matches = sum(1 for ind in py_indicators if ind in header)
    return matches >= 2


def _looks_like_js_ts(content: str) -> bool:
    """Quick heuristic: does this content look like JavaScript/TypeScript?"""
    indicators = [
        "function ", "const ", "let ", "var ", "=> ", "require(",
        "import ", "export ", "interface ", "type ", "async ",
    ]
    header = content[:2000]
    matches = sum(1 for ind in indicators if ind in header)
    return matches >= 2


# ---------------------------------------------------------------------------
# Main filter pipeline
# ---------------------------------------------------------------------------

def _build_checks(
    mode: FilterMode,
    languages: list[str] | None = None,
) -> list[tuple]:
    """Build the check list based on filter mode and selected languages.

    CONSERVATIVE: Only the base checks with generous thresholds.
                  Rejects clearly bad code. Passes anything ambiguous.

    STRICT:       Base checks with tighter thresholds, PLUS additional
                  checks for code quality, naming, documentation, etc.
                  Rejects anything that isn't clearly good.

    Language-aware: If languages are specified, only include syntax
    checks for those languages. This prevents e.g. TypeScript files
    being rejected by the Python AST parser.

    Returns:
        List of (check_function, args_dict) tuples.
    """
    has_python = languages is None or "python" in languages
    has_js_ts = languages is None or any(
        lang in languages for lang in ("typescript", "javascript")
    )

    if mode == FilterMode.CONSERVATIVE:
        checks = [
            # (function, kwargs override)  — empty dict = use defaults
            (check_length, {}),
            (check_avg_line_length, {}),
            (check_max_line_length, {}),
            (check_character_diversity, {}),
            (check_not_autogenerated, {}),
            (check_not_data_file, {}),
            (check_comment_ratio, {}),
            (check_not_test_heavy, {}),
        ]
        if has_python:
            checks.append((check_python_parseable, {}))
        if has_js_ts:
            checks.append((check_js_ts_parseable, {}))
        return checks

    # STRICT mode: tighter thresholds + extra checks
    checks = [
        # --- Base checks with tighter thresholds ---
        (check_length, {"min_lines": 10, "max_lines": 5000}),
        (check_avg_line_length, {"max_avg": 120}),
        (check_max_line_length, {"max_len": 500}),
        (check_character_diversity, {"min_unique_ratio": 0.08}),
        (check_not_autogenerated, {}),
        (check_not_data_file, {}),
        (check_comment_ratio, {"max_comment_ratio": 0.60}),
        (check_not_test_heavy, {"max_test_ratio": 0.70}),
    ]
    if has_python:
        checks.append((check_python_parseable, {}))
    if has_js_ts:
        checks.append((check_js_ts_parseable, {}))
    # --- Strict-only checks ---
    checks.extend([
        (check_has_functions_or_classes, {}),
        (check_naming_quality, {}),
        (check_code_to_blank_ratio, {}),
        (check_no_obvious_copy_paste, {}),
        (check_has_some_documentation, {}),
        (check_no_hardcoded_secrets, {}),
    ])
    return checks


# Summary of what changes between modes:
#
# | Check                 | Conservative    | Strict           |
# |-----------------------|-----------------|------------------|
# | min_lines             | 5               | 10               |
# | max_lines             | 10,000          | 5,000            |
# | max_avg_line_length   | 200             | 120              |
# | max_single_line       | 1,000           | 500              |
# | char_diversity        | 5%              | 8%               |
# | max_comment_ratio     | 85%             | 60%              |
# | max_test_ratio        | 90%             | 70%              |
# | has_functions/classes  | -               | yes              |
# | naming_quality        | -               | avg >= 3 chars   |
# | code_to_blank_ratio   | -               | >= 50%           |
# | copy-paste detection  | -               | <= 30% duplicate |
# | has_documentation     | -               | yes              |
# | hardcoded secrets     | -               | yes              |


def filter_code(
    content: str,
    mode: FilterMode = FilterMode.CONSERVATIVE,
    languages: list[str] | None = None,
) -> tuple[bool, str]:
    """Run quality checks on a single code file.

    Args:
        content: The raw code file content.
        mode: FilterMode.CONSERVATIVE (default) or FilterMode.STRICT.
        languages: List of languages being trained on. If provided,
                   only runs syntax checks relevant to those languages.

    Returns:
        (keep, reason) — keep=True if the file passes all checks.
        If rejected, reason explains which check failed.
    """
    checks = _build_checks(mode, languages=languages)

    for check_fn, kwargs in checks:
        try:
            keep, reason = check_fn(content, **kwargs) if kwargs else check_fn(content)
            if not keep:
                return False, reason
        except Exception:
            if mode == FilterMode.STRICT:
                # In strict mode: if we can't analyze it, reject it.
                # We only keep code we're confident is good.
                return False, f"analysis_failed ({check_fn.__name__})"
            # In conservative mode: if a check crashes, pass through.
            continue

    return True, ""


def filtered_stream(
    source: Iterator[str],
    mode: FilterMode = FilterMode.CONSERVATIVE,
    stats: FilterStats | None = None,
    log_every: int = 10000,
    languages: list[str] | None = None,
) -> Iterator[str]:
    """Wrap a code stream with quality filtering.

    This is the main integration point. Wrap any Iterator[str] of code
    content, and it yields only the files that pass quality checks.

    Args:
        source: Iterator yielding raw code file contents.
        mode: FilterMode.CONSERVATIVE or FilterMode.STRICT.
        stats: Optional FilterStats to accumulate results. If None, creates one.
        log_every: Print progress every N files.
        languages: List of languages being trained on (for language-aware checks).

    Yields:
        Code file contents that passed all quality checks.
    """
    if stats is None:
        stats = FilterStats()

    mode_label = mode.value.upper()

    for content in source:
        keep, reason = filter_code(content, mode=mode, languages=languages)
        stats.record(keep, reason)

        if keep:
            yield content

        if stats.total % log_every == 0 and stats.total > 0:
            pct = stats.kept / stats.total * 100
            print(f"  [filter:{mode_label}] {stats.total:,} files processed, "
                  f"{stats.kept:,} kept ({pct:.1f}%)")
            # Show top 3 rejection reasons every 100k files
            if stats.total % (log_every * 10) == 0 and stats.reasons:
                top_reasons = sorted(
                    stats.reasons.items(), key=lambda x: -x[1],
                )[:3]
                reasons_str = ", ".join(
                    f"{r}: {c:,}" for r, c in top_reasons
                )
                print(f"    Top rejections: {reasons_str}")

    # Print final summary
    print(stats.summary())


def _filter_worker(args: tuple[str, str, list[str] | None]) -> tuple[bool, str]:
    """Worker function for parallel filtering. Must be top-level for pickling.

    Returns (keep, reason) only — the caller matches results back to content
    by index order (executor.map preserves order).
    """
    content, mode_value, languages = args
    mode = FilterMode(mode_value)
    keep, reason = filter_code(content, mode=mode, languages=languages)
    return keep, reason


def parallel_filtered_stream(
    source: Iterator[str],
    mode: FilterMode = FilterMode.CONSERVATIVE,
    stats: FilterStats | None = None,
    log_every: int = 10000,
    num_workers: int | None = None,
    languages: list[str] | None = None,
) -> Iterator[str]:
    """Quality filtering with multiprocessing for CPU-bound checks.

    Uses ProcessPoolExecutor with chunksize to amortize IPC overhead.
    The key optimization is chunksize=64 in executor.map() — this sends
    64 files per IPC call instead of 1, reducing serialization overhead
    by ~64x.

    Falls back to sequential filtered_stream() if num_workers=1.

    Args:
        source: Iterator yielding raw code file contents.
        mode: FilterMode.CONSERVATIVE or FilterMode.STRICT.
        stats: Optional FilterStats to accumulate results.
        log_every: Print progress every N files.
        num_workers: Number of worker processes. Default: CPU cores (up to 12).
        languages: List of languages being trained on (for language-aware checks).
    """
    if num_workers is None:
        num_workers = max(1, min(os.cpu_count() or 4, 12))

    if num_workers <= 1:
        yield from filtered_stream(
            source, mode=mode, stats=stats, log_every=log_every,
            languages=languages,
        )
        return

    if stats is None:
        stats = FilterStats()

    mode_label = mode.value.upper()
    # Large batch = keep all workers fed. Small batch = too much idle time.
    batch_size = num_workers * 64

    print(f"  [filter:{mode_label}] Using {num_workers} worker processes, "
          f"batch size {batch_size}, chunksize 64")

    with ProcessPoolExecutor(max_workers=num_workers) as executor:
        batch: list[str] = []

        for content in source:
            batch.append(content)

            if len(batch) >= batch_size:
                yield from _process_filter_batch(
                    executor, batch, mode, stats, log_every, mode_label,
                    languages=languages,
                )
                batch = []

        # Flush remaining
        if batch:
            yield from _process_filter_batch(
                executor, batch, mode, stats, log_every, mode_label,
                languages=languages,
            )

    print(stats.summary())


def _process_filter_batch(
    executor: ProcessPoolExecutor,
    batch: list[str],
    mode: FilterMode,
    stats: FilterStats,
    log_every: int,
    mode_label: str,
    languages: list[str] | None = None,
) -> Iterator[str]:
    """Submit a batch to the process pool and yield kept files.

    The chunksize=64 parameter is critical — it tells executor.map to
    send 64 items per IPC call instead of 1. This cuts serialization
    overhead dramatically.
    """
    args = [(text, mode.value, languages) for text in batch]

    # chunksize=64: send 64 files to each worker per IPC round trip
    results = executor.map(_filter_worker, args, chunksize=64)

    for content, (keep, reason) in zip(batch, results):
        stats.record(keep, reason)
        if keep:
            yield content

        if stats.total % log_every == 0 and stats.total > 0:
            pct = stats.kept / stats.total * 100
            print(
                f"  [filter:{mode_label}] {stats.total:,} files "
                f"processed, {stats.kept:,} kept ({pct:.1f}%)"
            )
            if stats.total % (log_every * 10) == 0 and stats.reasons:
                top_reasons = sorted(
                    stats.reasons.items(), key=lambda x: -x[1],
                )[:3]
                reasons_str = ", ".join(
                    f"{r}: {c:,}" for r, c in top_reasons
                )
                print(f"    Top rejections: {reasons_str}")
