"""Data quality filtering for code training data.

Filters out low-quality code files before they enter the training pipeline.
This runs between the download step and the tokenization step:

    Stream from HuggingFace → Quality Filter → Tokenize → Train

Design principle: this filter is CONSERVATIVE. It only rejects code that is
clearly bad. If it can't determine quality (e.g., language not supported for
parsing), it passes the file through. You lose nothing by using it — it
either improves your data or does nothing.

Every filter function returns (keep: bool, reason: str). The reason is logged
so you can see what's being filtered and adjust thresholds.
"""

import ast
import re
from dataclasses import dataclass, field
from typing import Iterator


@dataclass
class FilterStats:
    """Tracks how many files were kept vs rejected, and why."""

    total: int = 0
    kept: int = 0
    rejected: int = 0
    reasons: dict[str, int] = field(default_factory=dict)

    def record(self, kept: bool, reason: str = ""):
        self.total += 1
        if kept:
            self.kept += 1
        else:
            self.rejected += 1
            self.reasons[reason] = self.reasons.get(reason, 0) + 1

    def summary(self) -> str:
        lines = [
            f"Quality filter results:",
            f"  Total files:    {self.total:,}",
            f"  Kept:           {self.kept:,} ({self.kept / max(self.total, 1) * 100:.1f}%)",
            f"  Rejected:       {self.rejected:,} ({self.rejected / max(self.total, 1) * 100:.1f}%)",
        ]
        if self.reasons:
            lines.append("  Rejection reasons:")
            for reason, count in sorted(self.reasons.items(), key=lambda x: -x[1]):
                lines.append(f"    {reason}: {count:,}")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Individual filter functions
# Each returns (keep, reason). keep=True means the file passes.
# ---------------------------------------------------------------------------

def check_length(content: str, min_lines: int = 5, max_lines: int = 10000) -> tuple[bool, str]:
    """Reject files that are too short or too long.

    Very short files (< 5 lines) are usually empty boilerplate or configs.
    Very long files (> 10K lines) are often auto-generated or bundled.
    """
    line_count = content.count("\n") + 1
    if line_count < min_lines:
        return False, f"too_short ({line_count} lines)"
    if line_count > max_lines:
        return False, f"too_long ({line_count} lines)"
    return True, ""


def check_avg_line_length(content: str, max_avg: int = 200) -> tuple[bool, str]:
    """Reject files with extremely long average line length.

    Minified code (JS/CSS bundles) has very long lines. Normal code
    averages 30-60 characters per line. If the average exceeds 200,
    it's almost certainly minified or auto-generated.
    """
    lines = content.split("\n")
    if not lines:
        return False, "empty"
    avg_len = sum(len(line) for line in lines) / len(lines)
    if avg_len > max_avg:
        return False, f"minified (avg line {avg_len:.0f} chars)"
    return True, ""


def check_max_line_length(content: str, max_len: int = 1000) -> tuple[bool, str]:
    """Reject files with any single extremely long line.

    A single line over 1000 chars is a strong signal of minified/generated code,
    base64 blobs, or embedded data.
    """
    for line in content.split("\n"):
        if len(line) > max_len:
            return False, f"long_line ({len(line)} chars)"
    return True, ""


def check_not_autogenerated(content: str) -> tuple[bool, str]:
    """Reject files that appear to be auto-generated.

    Checks for common auto-generation markers in the first 10 lines.
    """
    # Only check the header — auto-gen comments are always at the top
    header = "\n".join(content.split("\n")[:10]).lower()

    markers = [
        "auto-generated",
        "autogenerated",
        "automatically generated",
        "do not edit",
        "do not modify",
        "generated by",
        "generated from",
        "this file is generated",
        "machine generated",
        "code generated by",
        # Common generators
        "generated by the protocol buffer compiler",
        "generated by django",
        "generated by swagger",
        "generated by openapi",
    ]

    for marker in markers:
        if marker in header:
            return False, f"autogenerated ({marker})"

    return True, ""


def check_not_data_file(content: str) -> tuple[bool, str]:
    """Reject files that are mostly data rather than code.

    Data files (JSON dumps, CSV, SQL dumps, hex dumps) are common in repos
    but don't teach the model useful code patterns.
    """
    lines = content.split("\n")
    if not lines:
        return False, "empty"

    # Sample first 50 lines to check patterns
    sample = lines[:50]
    sample_text = "\n".join(sample)

    # Check for JSON array/object dumps (many lines starting with { or [)
    brace_lines = sum(1 for l in sample if l.strip().startswith(("{", "[", "]", "}")))
    if len(sample) > 10 and brace_lines / len(sample) > 0.8:
        return False, "data_file (JSON-like)"

    # Check for hex dumps or base64 blocks
    hex_pattern = re.compile(r"^[0-9a-fA-F\s]{40,}$")
    hex_lines = sum(1 for l in sample if hex_pattern.match(l.strip()))
    if len(sample) > 10 and hex_lines / len(sample) > 0.5:
        return False, "data_file (hex/binary)"

    # Check for CSV-like data (many lines with same number of commas)
    if len(sample) > 10:
        comma_counts = [l.count(",") for l in sample if l.strip()]
        if comma_counts and min(comma_counts) > 3:
            # Many commas and consistent count → probably CSV
            avg = sum(comma_counts) / len(comma_counts)
            variance = sum((c - avg) ** 2 for c in comma_counts) / len(comma_counts)
            if variance < 2.0 and avg > 5:
                return False, "data_file (CSV-like)"

    return True, ""


def check_not_test_heavy(content: str, max_test_ratio: float = 0.9) -> tuple[bool, str]:
    """Allow test files but reject files that are purely assertion dumps.

    Normal test files are fine training data. But some repos contain
    auto-generated test files with thousands of assert lines and no
    real logic — these aren't useful.
    """
    lines = [l.strip() for l in content.split("\n") if l.strip()]
    if len(lines) < 20:
        return True, ""  # Too short to judge

    assert_lines = sum(
        1 for l in lines
        if l.startswith("assert") or l.startswith("self.assert") or l.startswith("expect(")
    )
    ratio = assert_lines / len(lines)
    if ratio > max_test_ratio:
        return False, f"assertion_dump ({ratio:.0%} assert lines)"

    return True, ""


def check_python_parseable(content: str) -> tuple[bool, str]:
    """For Python files: reject if the code doesn't parse.

    If Python's own parser rejects the file, the code has syntax errors.
    The model shouldn't learn from broken code.

    Only applies to files that look like Python (checked by heuristics).
    Non-Python files always pass this check.
    """
    # Only attempt parsing if it looks like Python
    if not _looks_like_python(content):
        return True, ""  # Not Python — pass through

    try:
        ast.parse(content)
        return True, ""
    except SyntaxError:
        return False, "python_syntax_error"


def check_js_ts_parseable(content: str) -> tuple[bool, str]:
    """For JS/TS files: basic syntax sanity check.

    We can't fully parse JS/TS without a real parser (which would be a heavy
    dependency). Instead, check for basic structural issues:
    - Unbalanced braces
    - Obvious truncation

    Non-JS/TS files always pass this check.
    """
    if not _looks_like_js_ts(content):
        return True, ""  # Not JS/TS — pass through

    # Check brace balance (rough check — doesn't handle strings/comments)
    open_braces = content.count("{")
    close_braces = content.count("}")
    imbalance = abs(open_braces - close_braces)

    # Allow small imbalance (template literals, regex, etc. can confuse counting)
    if imbalance > 5 and imbalance / max(open_braces, 1) > 0.2:
        return False, f"js_brace_imbalance ({open_braces} open, {close_braces} close)"

    return True, ""


def check_character_diversity(content: str, min_unique_ratio: float = 0.05) -> tuple[bool, str]:
    """Reject files with very low character diversity.

    Files that are mostly one repeated character or pattern are not useful.
    Normal code uses at least 30-40 unique characters.
    """
    if len(content) < 100:
        return True, ""  # Too short to judge

    unique_chars = len(set(content))
    total_chars = len(content)
    ratio = unique_chars / min(total_chars, 1000)  # Cap denominator for long files

    if ratio < min_unique_ratio:
        return False, f"low_diversity ({unique_chars} unique chars)"

    return True, ""


def check_comment_ratio(content: str, max_comment_ratio: float = 0.85) -> tuple[bool, str]:
    """Reject files that are almost entirely comments.

    License files, documentation headers, and comment-only files
    don't help the model learn code patterns.
    """
    lines = [l.strip() for l in content.split("\n") if l.strip()]
    if len(lines) < 10:
        return True, ""  # Too short to judge

    comment_lines = sum(
        1 for l in lines
        if l.startswith("#") or l.startswith("//") or l.startswith("/*")
        or l.startswith("*") or l.startswith("'''") or l.startswith('"""')
    )
    ratio = comment_lines / len(lines)
    if ratio > max_comment_ratio:
        return False, f"mostly_comments ({ratio:.0%})"

    return True, ""


# ---------------------------------------------------------------------------
# Heuristics for language detection
# ---------------------------------------------------------------------------

def _looks_like_python(content: str) -> bool:
    """Quick heuristic: does this content look like Python?"""
    indicators = ["def ", "import ", "class ", "if __name__", "print(", "self."]
    header = content[:2000]
    matches = sum(1 for ind in indicators if ind in header)
    return matches >= 2


def _looks_like_js_ts(content: str) -> bool:
    """Quick heuristic: does this content look like JavaScript/TypeScript?"""
    indicators = [
        "function ", "const ", "let ", "var ", "=> ", "require(",
        "import ", "export ", "interface ", "type ", "async ",
    ]
    header = content[:2000]
    matches = sum(1 for ind in indicators if ind in header)
    return matches >= 2


# ---------------------------------------------------------------------------
# Main filter pipeline
# ---------------------------------------------------------------------------

# All checks in order. Each is (function, name).
# Order matters slightly for performance — cheap checks first.
ALL_CHECKS = [
    (check_length, "length"),
    (check_avg_line_length, "avg_line_length"),
    (check_max_line_length, "max_line_length"),
    (check_character_diversity, "char_diversity"),
    (check_not_autogenerated, "autogenerated"),
    (check_not_data_file, "data_file"),
    (check_comment_ratio, "comment_ratio"),
    (check_not_test_heavy, "test_heavy"),
    (check_python_parseable, "python_parse"),
    (check_js_ts_parseable, "js_ts_parse"),
]


def filter_code(content: str) -> tuple[bool, str]:
    """Run all quality checks on a single code file.

    Args:
        content: The raw code file content.

    Returns:
        (keep, reason) — keep=True if the file passes all checks.
        If rejected, reason explains which check failed.
    """
    for check_fn, name in ALL_CHECKS:
        try:
            keep, reason = check_fn(content)
            if not keep:
                return False, reason
        except Exception:
            # If a check crashes, pass the file through.
            # We never reject code we can't properly analyze.
            continue

    return True, ""


def filtered_stream(
    source: Iterator[str],
    stats: FilterStats | None = None,
    log_every: int = 10000,
) -> Iterator[str]:
    """Wrap a code stream with quality filtering.

    This is the main integration point. Wrap any Iterator[str] of code
    content, and it yields only the files that pass quality checks.

    If a check fails or crashes on a file, the file passes through.
    This filter only REMOVES clearly bad data — it never blocks good data.

    Args:
        source: Iterator yielding raw code file contents.
        stats: Optional FilterStats to accumulate results. If None, creates one.
        log_every: Print progress every N files.

    Yields:
        Code file contents that passed all quality checks.
    """
    if stats is None:
        stats = FilterStats()

    for content in source:
        keep, reason = filter_code(content)
        stats.record(keep, reason)

        if keep:
            yield content

        if stats.total % log_every == 0 and stats.total > 0:
            pct = stats.kept / stats.total * 100
            print(f"  [filter] {stats.total:,} files processed, "
                  f"{stats.kept:,} kept ({pct:.1f}%)")

    # Print final summary
    print(stats.summary())
