"""Ollama Modelfile generation for cola-coder models.

Ollama uses a Modelfile format (similar to Dockerfile) to define models.
Once a GGUF file is available, this generates the Modelfile and prints
the command to register the model with `ollama create`.

Usage:
    exporter = OllamaExporter()
    modelfile_path = exporter.create_modelfile(
        gguf_path="exports/cola-coder-f16.gguf",
        output_dir="exports/",
        model_name="cola-coder",
    )
    # Then run: ollama create cola-coder -f exports/Modelfile
"""

from __future__ import annotations

from pathlib import Path


class OllamaExporter:
    """Create an Ollama Modelfile for easy local deployment.

    The generated Modelfile configures:
    - The GGUF file path (FROM directive)
    - Chat template (LLaMA-style)
    - Sensible defaults for code generation (temperature, top-p, etc.)
    """

    # LLaMA-style chat template — matches the training format used by
    # most code-focused models based on the LLaMA architecture.
    _CHAT_TEMPLATE = (
        "{{ if .System }}<|start_header_id|>system<|end_header_id|>\n\n"
        "{{ .System }}<|eot_id|>{{ end }}"
        "{{ range .Messages }}<|start_header_id|>{{ .Role }}<|end_header_id|>\n\n"
        "{{ .Content }}<|eot_id|>{{ end }}"
        "<|start_header_id|>assistant<|end_header_id|>\n\n"
    )

    def create_modelfile(
        self,
        gguf_path: str,
        output_dir: str,
        model_name: str = "cola-coder",
    ) -> str:
        """Create a Modelfile for `ollama create`.

        Args:
            gguf_path: Absolute or relative path to the exported .gguf file.
            output_dir: Directory to write the Modelfile into.
            model_name: The name to use with `ollama create <name>`.

        Returns:
            Absolute path to the generated Modelfile.
        """
        gguf_path_obj = Path(gguf_path).resolve()
        output_dir_obj = Path(output_dir)
        output_dir_obj.mkdir(parents=True, exist_ok=True)

        modelfile_path = output_dir_obj / "Modelfile"
        content = self._build_modelfile(gguf_path_obj, model_name)
        modelfile_path.write_text(content, encoding="utf-8")

        # Also write a helper script
        readme_path = output_dir_obj / "README_ollama.txt"
        readme_path.write_text(self._build_readme(modelfile_path, model_name), encoding="utf-8")

        return str(modelfile_path.resolve())

    # ── Private helpers ───────────────────────────────────────────────────────

    def _build_modelfile(self, gguf_path: Path, model_name: str) -> str:
        """Build the Modelfile content string."""
        lines = [
            f"# Modelfile for {model_name}",
            "# Generated by cola-coder export tooling",
            f"# Run: ollama create {model_name} -f Modelfile",
            "",
            f"FROM {gguf_path}",
            "",
            "# Chat template (LLaMA 3 style)",
            f'TEMPLATE """{self._CHAT_TEMPLATE}"""',
            "",
            "# System prompt for code generation",
            'SYSTEM """You are cola-coder, an AI assistant specialised in TypeScript, '
            "JavaScript, and modern web development. You write clean, well-typed code "
            'with clear explanations."""',
            "",
            "# Generation parameters",
            "PARAMETER temperature 0.7",
            "PARAMETER top_p 0.9",
            "PARAMETER top_k 40",
            "PARAMETER repeat_penalty 1.1",
            "PARAMETER num_predict 512",
            "PARAMETER stop <|eot_id|>",
            "PARAMETER stop <|end_of_text|>",
        ]
        return "\n".join(lines) + "\n"

    def _build_readme(self, modelfile_path: Path, model_name: str) -> str:
        """Build usage instructions."""
        return (
            f"Cola-coder Ollama Setup\n"
            f"======================\n\n"
            f"1. Make sure Ollama is installed (https://ollama.ai)\n\n"
            f"2. Register the model:\n"
            f"   ollama create {model_name} -f {modelfile_path}\n\n"
            f"3. Run the model:\n"
            f"   ollama run {model_name}\n\n"
            f"4. Or use the API:\n"
            f"   curl http://localhost:11434/api/generate -d '{{\n"
            f'     "model": "{model_name}",\n'
            f'     "prompt": "Write a TypeScript function that"\n'
            f"   }}'\n"
        )
