"""Ollama Modelfile generation for cola-coder models.

Ollama uses a Modelfile format (similar to Dockerfile) to define models.
Once a GGUF file is available, this generates the Modelfile and prints
the command to register the model with `ollama create`.

Usage:
    exporter = OllamaExporter()
    modelfile_path = exporter.create_modelfile(
        gguf_path="exports/cola-coder-f16.gguf",
        output_dir="exports/",
        model_name="cola-coder",
    )
    # Then run: ollama create cola-coder -f exports/Modelfile
"""

from __future__ import annotations

from pathlib import Path

# These MUST match cola_coder.tokenizer.chat_template.IM_START / IM_END — the
# ChatML format cola-coder is actually trained on (SFT) — and the base <|eos|>
# token. They are defined as literals here to keep this module torch-free
# (chat_template imports the Transformer / torch); test_ollama_chatml asserts
# they stay in sync with the canonical constants.
_IM_START = "<|im_start|>"
_IM_END = "<|im_end|>"
_EOS = "<|eos|>"


class OllamaExporter:
    """Create an Ollama Modelfile for easy local deployment.

    The generated Modelfile configures:
    - The GGUF file path (FROM directive)
    - Chat template (ChatML — the format cola-coder is trained on)
    - Sensible defaults for code generation (temperature, top-p, etc.)
    """

    # ChatML template — matches cola_coder.tokenizer.chat_template (the format
    # used during SFT: <|im_start|>{role}\n{content}<|im_end|>). The previous
    # LLaMA-3 template (<|start_header_id|>/<|eot_id|>) used tokens that are NOT
    # in cola-coder's vocabulary, so an exported Ollama model would fragment the
    # template and never see its trained chat tokens — broken instruction
    # following (the BUG-106 family, on the Ollama-export side).
    _CHAT_TEMPLATE = (
        "{{ if .System }}" + _IM_START + "system\n"
        "{{ .System }}" + _IM_END + "\n{{ end }}"
        "{{ range .Messages }}" + _IM_START + "{{ .Role }}\n"
        "{{ .Content }}" + _IM_END + "\n{{ end }}"
        + _IM_START + "assistant\n"
    )

    def create_modelfile(
        self,
        gguf_path: str,
        output_dir: str,
        model_name: str = "cola-coder",
    ) -> str:
        """Create a Modelfile for `ollama create`.

        Args:
            gguf_path: Absolute or relative path to the exported .gguf file.
            output_dir: Directory to write the Modelfile into.
            model_name: The name to use with `ollama create <name>`.

        Returns:
            Absolute path to the generated Modelfile.
        """
        gguf_path_obj = Path(gguf_path).resolve()
        output_dir_obj = Path(output_dir)
        output_dir_obj.mkdir(parents=True, exist_ok=True)

        modelfile_path = output_dir_obj / "Modelfile"
        content = self._build_modelfile(gguf_path_obj, model_name)
        modelfile_path.write_text(content, encoding="utf-8")

        # Also write a helper script
        readme_path = output_dir_obj / "README_ollama.txt"
        readme_path.write_text(self._build_readme(modelfile_path, model_name), encoding="utf-8")

        return str(modelfile_path.resolve())

    # ── Private helpers ───────────────────────────────────────────────────────

    def _build_modelfile(self, gguf_path: Path, model_name: str) -> str:
        """Build the Modelfile content string."""
        lines = [
            f"# Modelfile for {model_name}",
            "# Generated by cola-coder export tooling",
            f"# Run: ollama create {model_name} -f Modelfile",
            "",
            f"FROM {gguf_path}",
            "",
            "# Chat template (ChatML — matches cola-coder's SFT format)",
            f'TEMPLATE """{self._CHAT_TEMPLATE}"""',
            "",
            "# System prompt for code generation",
            'SYSTEM """You are cola-coder, an AI assistant specialised in TypeScript, '
            "JavaScript, and modern web development. You write clean, well-typed code "
            'with clear explanations."""',
            "",
            "# Generation parameters",
            "PARAMETER temperature 0.7",
            "PARAMETER top_p 0.9",
            "PARAMETER top_k 40",
            "PARAMETER repeat_penalty 1.1",
            "PARAMETER num_predict 512",
            f"PARAMETER stop {_IM_END}",
            f"PARAMETER stop {_EOS}",
        ]
        return "\n".join(lines) + "\n"

    def _build_readme(self, modelfile_path: Path, model_name: str) -> str:
        """Build usage instructions."""
        return (
            f"Cola-coder Ollama Setup\n"
            f"======================\n\n"
            f"1. Make sure Ollama is installed (https://ollama.ai)\n\n"
            f"2. Register the model:\n"
            f"   ollama create {model_name} -f {modelfile_path}\n\n"
            f"3. Run the model:\n"
            f"   ollama run {model_name}\n\n"
            f"4. Or use the API:\n"
            f"   curl http://localhost:11434/api/generate -d '{{\n"
            f'     "model": "{model_name}",\n'
            f'     "prompt": "Write a TypeScript function that"\n'
            f"   }}'\n"
        )
