"""Content quality filter for auto-generated, data dump, and low-signal files.

Detects and rejects files that are auto-generated (protobuf, swagger/openapi,
etc.), minified code, CSV/JSON data dumps, and files with massive string
literals or other low-signal patterns.
"""

import logging
import re

from cola_coder.data.registry import register_filter

logger = logging.getLogger(__name__)


@register_filter("content")
class ContentFilter:
    """Reject autogenerated, data dump, and low-signal files.

    This filter catches patterns that the basic quality filter might miss:
    - Protocol buffer generated code
    - Swagger/OpenAPI generated code
    - Minified JavaScript/CSS
    - CSV/JSON/XML data dumps
    - Files dominated by massive string literals
    - Lock files and dependency manifests
    """

    # Auto-generation markers (checked in first 20 lines)
    AUTOGEN_MARKERS = [
        "auto-generated",
        "autogenerated",
        "automatically generated",
        "do not edit",
        "do not modify",
        "generated by",
        "generated from",
        "this file is generated",
        "machine generated",
        "code generated by",
        "generated by the protocol buffer compiler",
        "generated by django",
        "generated by swagger",
        "generated by openapi",
        "generated by protoc",
        "generated by grpc",
        "generated by thrift",
        "generated by flatbuffers",
        "generated by antlr",
        "generated code -- do not edit",
        "@generated",
        "this is a generated file",
    ]

    # File content patterns that indicate generated/data files
    _MINIFIED_RE = re.compile(
        r'^[^\n]{500,}$',  # A single line over 500 chars
        re.MULTILINE,
    )

    _LONG_STRING_RE = re.compile(
        r'["\'][^"\']{1000,}["\']',  # String literal over 1000 chars
    )

    _BASE64_RE = re.compile(
        r'[A-Za-z0-9+/=]{100,}',  # Long base64 blocks
    )

    def __init__(
        self,
        max_autogen_markers: int = 0,
        max_long_string_ratio: float = 0.3,
        max_avg_line_length: int = 200,
    ):
        """
        Args:
            max_autogen_markers: Max autogen markers allowed (0 = reject any).
            max_long_string_ratio: Max fraction of content in long strings.
            max_avg_line_length: Max average line length before flagging as minified.
        """
        self.max_autogen_markers = max_autogen_markers
        self.max_long_string_ratio = max_long_string_ratio
        self.max_avg_line_length = max_avg_line_length

    def name(self) -> str:
        return "content"

    def _check_autogenerated(self, content: str) -> tuple[bool, str]:
        """Check for auto-generation markers in the file header.

        Counts how many distinct AUTOGEN_MARKERS phrases appear in the first 20
        lines and rejects when that COUNT exceeds ``max_autogen_markers``
        (0 = reject on any marker). Previously this returned on the FIRST marker
        regardless of the threshold, so ``max_autogen_markers`` was a silent
        no-op for any value > 0 (the default behavior is unchanged).
        """
        header = "\n".join(content.split("\n")[:20]).lower()
        found = [marker for marker in self.AUTOGEN_MARKERS if marker in header]
        if len(found) > self.max_autogen_markers:
            return False, f"autogenerated ({found[0]})"
        return True, ""

    def _check_minified(self, content: str) -> tuple[bool, str]:
        """Check if the file is minified code."""
        lines = content.split("\n")
        if not lines:
            return True, ""

        # Average line length check
        total_len = sum(len(line) for line in lines)
        avg_len = total_len / len(lines)
        if avg_len > self.max_avg_line_length:
            return False, f"minified_code (avg line length {avg_len:.0f})"

        # Check for very few lines but very long content (minified JS/CSS)
        if len(lines) < 5 and len(content) > 5000:
            return False, "minified_code (few lines, large content)"

        return True, ""

    def _check_data_dump(self, content: str) -> tuple[bool, str]:
        """Check if the file is a data dump (JSON, CSV, etc.)."""
        lines = content.split("\n")
        if len(lines) < 10:
            return True, ""

        sample = lines[:100]

        # JSON array/object dumps: many lines starting with { [ ] }
        brace_lines = sum(
            1 for line in sample
            if line.strip().startswith(("{", "[", "]", "}"))
        )
        if brace_lines / len(sample) > 0.8:
            return False, "data_dump (JSON-like structure)"

        # CSV detection: consistent comma count across lines
        non_empty = [line for line in sample if line.strip()]
        if len(non_empty) > 10:
            comma_counts = [line.count(",") for line in non_empty]
            if min(comma_counts) > 3:
                avg = sum(comma_counts) / len(comma_counts)
                variance = sum((c - avg) ** 2 for c in comma_counts) / len(comma_counts)
                if variance < 2.0 and avg > 5:
                    return False, "data_dump (CSV-like structure)"

        # XML/HTML data dumps: mostly tags
        tag_lines = sum(
            1 for line in sample
            if line.strip().startswith("<") and line.strip().endswith(">")
        )
        if len(sample) > 10 and tag_lines / len(sample) > 0.8:
            return False, "data_dump (XML/HTML-like structure)"

        return True, ""

    def _check_string_heavy(self, content: str) -> tuple[bool, str]:
        """Check if the file is dominated by massive string literals."""
        if not content:
            return True, ""

        long_strings = self._LONG_STRING_RE.findall(content)
        if not long_strings:
            return True, ""

        total_string_len = sum(len(s) for s in long_strings)
        ratio = total_string_len / len(content)

        if ratio > self.max_long_string_ratio:
            return False, f"string_heavy ({ratio:.0%} in long string literals)"

        return True, ""

    def _check_base64_heavy(self, content: str) -> tuple[bool, str]:
        """Check if the file contains large base64 encoded blocks."""
        if not content:
            return True, ""

        base64_matches = self._BASE64_RE.findall(content)
        if not base64_matches:
            return True, ""

        total_b64_len = sum(len(m) for m in base64_matches)
        ratio = total_b64_len / len(content)

        if ratio > 0.3:
            return False, f"base64_heavy ({ratio:.0%} base64 content)"

        return True, ""

    def _check_lock_file(self, content: str) -> tuple[bool, str]:
        """Check if the file is a dependency lock file."""
        lines = content.split("\n")
        header = "\n".join(lines[:5]).lower()

        lock_indicators = [
            "# this file is autogenerated",  # yarn.lock, pip
            '"lockfileversion"',              # package-lock.json
            "lockfileversion",                # package-lock.json
            "# frozen_string_literal",        # Gemfile.lock pattern
        ]

        for indicator in lock_indicators:
            if indicator in header:
                return False, "lock_file"

        return True, ""

    def check(self, record) -> tuple[bool, str]:
        """Run all content quality checks.

        Args:
            record: Object with .content (str) and .metadata (dict) attributes.

        Returns:
            (keep, reason) tuple.
        """
        content = record.content
        if not content:
            return True, ""

        # Run all sub-checks in priority order (cheapest first)
        checks = [
            self._check_autogenerated,
            self._check_lock_file,
            self._check_minified,
            self._check_data_dump,
            self._check_string_heavy,
            self._check_base64_heavy,
        ]

        for check_fn in checks:
            keep, reason = check_fn(content)
            if not keep:
                return False, reason

        return True, ""

    def setup(self, config: dict) -> None:
        """Optional setup from config dict."""
        if "max_autogen_markers" in config:
            self.max_autogen_markers = config["max_autogen_markers"]
        if "max_long_string_ratio" in config:
            self.max_long_string_ratio = config["max_long_string_ratio"]
        if "max_avg_line_length" in config:
            self.max_avg_line_length = config["max_avg_line_length"]
